import os
from dotenv import load_dotenv

load_dotenv()

SECRET_KEY = os.getenv("SECRET_KEY")
SQLALCHEMY_DATABASE_URI = os.getenv("SQLALCHEMY_DATABASE_URI")
SQLALCHEMY_TRACK_MODIFICATIONS = os.getenv("SQLALCHEMY_TRACK_MODIFICATIONS")
SQLALCHEMY_ECHO = os.getenv("SQLALCHEMY_ECHO")
CORS_HEADERS = os.getenv("CORS_HEADERS")

MAIL_SERVER = os.getenv("MAIL_SERVER")
MAIL_PORT = os.getenv("MAIL_PORT")
MAIL_USE_TLS = os.getenv("MAIL_USE_TLS")
MAIL_USERNAME = os.getenv("MAIL_USERNAME")
MAIL_DEFAULT_SENDER = os.getenv("MAIL_DEFAULT_SENDER")
MAIL_PASSWORD = os.getenv("MAIL_PASSWORD")

ADMIN_ROLE_ID = os.getenv("ADMIN_ROLE_ID")
FACULTY_ROLE_ID = os.getenv("FACULTY_ROLE_ID")
DEPARTMENT_ROLE_ID = os.getenv("DEPARTMENT_ROLE_ID")

