from .PE_amount_in_first_block_check import PEAmountInFirstBlockTest
from .base_test import BaseTest
from .compulsory_disciplines_check import CompulsoryDisciplinesCheck
from .min_discipline_zet import MinDisciplineZet
from .optional_pe_amount import OptionalPEAmount
from .total_zet_check import TotalZetTest
from .zet_check_by_block import ZetCheckByFirstBlock, ZetCheckBySecondBlock, ZetCheckByThirdBlock
from .zet_check_by_year import ZetCheckByYear