"""del fk

Revision ID: 01404b5cbe42
Revises: 5adc6a929574
Create Date: 2023-02-16 18:49:55.300552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01404b5cbe42'
down_revision = '5adc6a929574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.create_foreign_key('aup_data_ibfk_2', 'tbl_aup', ['id_aup'], ['id_aup'], ondelete='CASCADE')

    # ### end Alembic commands ###
