"""Add category_name to Competency model

Revision ID: 05451f9d4309
Revises: e98177595542
Create Date: 2025-05-25 09:30:51.548219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05451f9d4309'
down_revision = 'e98177595542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competencies_competency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(length=255), nullable=True, comment='Название категории компетенции'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competencies_competency', schema=None) as batch_op:
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
