"""empty message

Revision ID: 05ca5e6878c1
Revises: d8f492524ded
Create Date: 2023-02-16 17:50:40.436292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ca5e6878c1'
down_revision = 'd8f492524ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'd_period', ['id_period'], ['id_period'])
        batch_op.create_foreign_key(None, 'd_blocks', ['id_block'], ['id_block'])
        batch_op.create_foreign_key(None, 'd_part', ['id_part'], ['id_part'])
        batch_op.create_foreign_key(None, 'd_control_type', ['id_type_control'], ['id_type_control'])
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'])
        batch_op.create_foreign_key(None, 'd_type_record', ['id_type_record'], ['id_type_record'])
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id_module'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
