"""add fk aup

Revision ID: 0708728120c5
Revises: 81a9c28c676d
Create Date: 2023-02-16 18:55:19.030074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0708728120c5'
down_revision = '81a9c28c676d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tbl_aup', ['id_aup'], ['id_aup'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
