"""add date and time in topic

Revision ID: 1236bd112f40
Revises: 44b5a167b575
Create Date: 2024-05-19 18:08:12.909197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1236bd112f40'
down_revision = '44b5a167b575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_type', schema=None) as batch_op:
        batch_op.alter_column('min_grade',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_grade',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('archived',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('datetime_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('datetime_finish', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_task_finish', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_column('date_task_finish')
        batch_op.drop_column('datetime_finish')
        batch_op.drop_column('datetime_start')
        batch_op.drop_column('date')

    with op.batch_alter_table('grade_type', schema=None) as batch_op:
        batch_op.alter_column('archived',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('max_grade',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('min_grade',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
