"""del models and some fix

Revision ID: 1314ea44e3de
Revises: d989448a2130
Create Date: 2023-01-18 00:15:27.124636

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1314ea44e3de'
down_revision = 'd989448a2130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_module')
    with op.batch_alter_table('work_map', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tbl_group', ['id_group'], ['id_group'])
        batch_op.drop_column('id_module')

    with op.batch_alter_table('workload', schema=None) as batch_op:
        batch_op.drop_constraint('workload_ibfk_2', type_='foreignkey')
        batch_op.drop_column('id_module')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_module', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('workload_ibfk_2', 'tbl_module', ['id_module'], ['id_module'])

    with op.batch_alter_table('work_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_module', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('tbl_module',
    sa.Column('id_module', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name_module', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('color', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_module'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
