"""empty message

Revision ID: 133fdeafa952
Revises: 13b16b4166c8
Create Date: 2023-02-16 16:28:44.585926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '133fdeafa952'
down_revision = '13b16b4166c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d_part',
    sa.Column('id_part', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_part')
    )
    op.create_table('spr_branch',
    sa.Column('id_branch', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_branch')
    )
    op.create_table('spr_degree_education',
    sa.Column('id_degree', sa.Integer(), nullable=False),
    sa.Column('name_deg', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_degree')
    )
    op.create_table('spr_form_education',
    sa.Column('id_form', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_form')
    )
    op.create_table('spr_okco',
    sa.Column('program_code', sa.String(length=255), nullable=False),
    sa.Column('name_okco', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('program_code')
    )
    op.create_table('spr_rop',
    sa.Column('id_rop', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('middle_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_rop')
    )
    op.create_table('spr_standard_zet',
    sa.Column('id_standard', sa.Integer(), nullable=False),
    sa.Column('type_standard', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_standard')
    )
    op.create_table('spr_faculty',
    sa.Column('id_faculty', sa.Integer(), nullable=False),
    sa.Column('name_faculty', sa.String(length=255), nullable=False),
    sa.Column('id_branch', sa.Integer(), nullable=False),
    sa.Column('dean', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_branch'], ['spr_branch.id_branch'], ),
    sa.PrimaryKeyConstraint('id_faculty')
    )
    op.create_table('spr_name_op',
    sa.Column('id_spec', sa.Integer(), nullable=False),
    sa.Column('program_code', sa.String(length=255), nullable=False),
    sa.Column('num_profile', sa.String(length=255), nullable=False),
    sa.Column('name_spec', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['program_code'], ['spr_okco.program_code'], ),
    sa.PrimaryKeyConstraint('id_spec')
    )
    op.create_table('spr_volume_degree_zet',
    sa.Column('id_volume_deg', sa.Integer(), nullable=False),
    sa.Column('program_code', sa.String(length=255), nullable=False),
    sa.Column('id_standard', sa.Integer(), nullable=False),
    sa.Column('zet', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['program_code'], ['spr_okco.program_code'], ),
    sa.PrimaryKeyConstraint('id_volume_deg')
    )
    op.create_table('tbl_duration_edu',
    sa.Column('id_duration', sa.Integer(), nullable=False),
    sa.Column('id_degree', sa.Integer(), nullable=False),
    sa.Column('id_form', sa.Integer(), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=True),
    sa.Column('id_spec', sa.Integer(), nullable=False),
    sa.Column('year_beg', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_degree'], ['spr_degree_education.id_degree'], ),
    sa.ForeignKeyConstraint(['id_form'], ['spr_form_education.id_form'], ),
    sa.ForeignKeyConstraint(['id_spec'], ['spr_name_op.id_spec'], ),
    sa.PrimaryKeyConstraint('id_duration')
    )
    op.create_table('tbl_op',
    sa.Column('id_op', sa.Integer(), nullable=False),
    sa.Column('id_duration', sa.Integer(), nullable=False),
    sa.Column('id_faculty', sa.Integer(), nullable=False),
    sa.Column('id_rop', sa.Integer(), nullable=False),
    sa.Column('type_educ', sa.String(length=255), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=False),
    sa.Column('type_standard', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('period_educ', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_duration'], ['tbl_duration_edu.id_duration'], ),
    sa.ForeignKeyConstraint(['id_faculty'], ['spr_faculty.id_faculty'], ),
    sa.ForeignKeyConstraint(['id_rop'], ['spr_rop.id_rop'], ),
    sa.PrimaryKeyConstraint('id_op')
    )
    op.create_table('tbl_aup',
    sa.Column('id_aup', sa.Integer(), nullable=False),
    sa.Column('id_op', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('num_aup', sa.String(length=255), nullable=False),
    sa.Column('base', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_op'], ['tbl_op.id_op'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_aup')
    )
    op.drop_table('aup_info')
    op.drop_table('d_chast')
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_aup', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_block', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_part', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_module', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_group', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_type_record', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_period', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('id_type_control', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'd_control_type', ['id_type_control'], ['id_type_control'])
        batch_op.create_foreign_key(None, 'tbl_aup', ['id_aup'], ['id_aup'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'd_part', ['id_part'], ['id_part'])
        batch_op.create_foreign_key(None, 'd_type_record', ['id_type_record'], ['id_type_record'])
        batch_op.create_foreign_key(None, 'd_period', ['id_period'], ['id_period'])
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id_module'])
        batch_op.create_foreign_key(None, 'd_blocks', ['id_block'], ['id_block'])
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'])
        batch_op.drop_column('type_control_id')
        batch_op.drop_column('block_id')
        batch_op.drop_column('module_id')
        batch_op.drop_column('type_id')
        batch_op.drop_column('aup_num')
        batch_op.drop_column('part_id')
        batch_op.drop_column('period_control_id')

    with op.batch_alter_table('d_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_block', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('d_control_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_type_control', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('d_ed_izmereniya', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_edizm', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('d_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_module', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('d_period', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_period', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('d_type_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_type_record', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_group', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('id_group')

    with op.batch_alter_table('d_type_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('id_type_record')

    with op.batch_alter_table('d_period', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('id_period')

    with op.batch_alter_table('d_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('id_module')

    with op.batch_alter_table('d_ed_izmereniya', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('id_edizm')

    with op.batch_alter_table('d_control_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('id_type_control')

    with op.batch_alter_table('d_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('id_block')

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_control_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('part_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('aup_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('module_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('block_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type_control_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_type_control')
        batch_op.drop_column('id_period')
        batch_op.drop_column('id_type_record')
        batch_op.drop_column('id_group')
        batch_op.drop_column('id_module')
        batch_op.drop_column('id_part')
        batch_op.drop_column('id_block')
        batch_op.drop_column('id_aup')

    op.create_table('d_chast',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('aup_info',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('num', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('qualification', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('department', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('base', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('full_years', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('type_education', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('degree', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('direction', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('program_code', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('name_spec', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('type_standard', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('name_faculty', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('form_educ', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('years_begin', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('period_edication', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('tbl_aup')
    op.drop_table('tbl_op')
    op.drop_table('tbl_duration_edu')
    op.drop_table('spr_volume_degree_zet')
    op.drop_table('spr_name_op')
    op.drop_table('spr_faculty')
    op.drop_table('spr_standard_zet')
    op.drop_table('spr_rop')
    op.drop_table('spr_okco')
    op.drop_table('spr_form_education')
    op.drop_table('spr_degree_education')
    op.drop_table('spr_branch')
    op.drop_table('d_part')
    # ### end Alembic commands ###
