"""bla

Revision ID: 13b01ad90cd2
Revises: 29c231241434
Create Date: 2024-05-31 03:35:57.935750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13b01ad90cd2'
down_revision = '29c231241434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_21', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_22', type_='foreignkey')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('grades_ibfk_3', type_='foreignkey')
        batch_op.drop_column('discipline_table_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discipline_table_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('grades_ibfk_3', 'grade_table', ['discipline_table_id'], ['id'])

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_22', 'groups', ['id_group'], ['id_group'])
        batch_op.create_foreign_key('aup_data_ibfk_21', 'd_modules', ['id_module'], ['id'])

    # ### end Alembic commands ###
