"""123

Revision ID: 163c9b7a5d59
Revises: 840ee06f6367
Create Date: 2023-03-14 20:50:28.358226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163c9b7a5d59'
down_revision = '840ee06f6367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_7', type_='foreignkey')
        batch_op.create_foreign_key(None, 'd_period', ['id_period'], ['id'], onupdate='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_7', 'd_period', ['id_period'], ['id'])

    # ### end Alembic commands ###
