"""empty message

Revision ID: 189e31699121
Revises: 5cc30f446f5d
Create Date: 2024-03-12 18:36:41.963217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189e31699121'
down_revision = '5cc30f446f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spr_faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_only', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spr_faculty', schema=None) as batch_op:
        batch_op.drop_column('admin_only')

    # ### end Alembic commands ###
