"""empty message

Revision ID: 1b06530a95df
Revises: 05ca5e6878c1
Create Date: 2023-02-16 18:27:07.234530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b06530a95df'
down_revision = '05ca5e6878c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'd_blocks', ['id_block'], ['id_block'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'd_type_record', ['id_type_record'], ['id_type_record'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'd_part', ['id_part'], ['id_part'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id_module'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'd_control_type', ['id_type_control'], ['id_type_control'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'd_period', ['id_period'], ['id_period'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
