"""add workload

Revision ID: 1da0a4d32ddb
Revises: 39393e9b4964
Create Date: 2022-09-30 15:34:53.784898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da0a4d32ddb'
down_revision = '39393e9b4964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workload',
    sa.Column('id_workload', sa.Integer(), nullable=False),
    sa.Column('id_aup', sa.Integer(), nullable=False),
    sa.Column('block', sa.String(length=255), nullable=False),
    sa.Column('cypher', sa.String(length=255), nullable=False),
    sa.Column('part', sa.String(length=255), nullable=False),
    sa.Column('id_module', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=255), nullable=False),
    sa.Column('discipline', sa.String(length=255), nullable=False),
    sa.Column('period', sa.String(length=255), nullable=False),
    sa.Column('load', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('measurement', sa.String(length=255), nullable=False),
    sa.Column('zet', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_aup'], ['tbl_aup.id_aup'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_module'], ['tbl_module.id_module'], ),
    sa.PrimaryKeyConstraint('id_workload')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workload')
    # ### end Alembic commands ###
