"""add program_code fk to SprVolumeDegreeZET

Revision ID: 2068f7bfe134
Revises: 561bf9dd5f91
Create Date: 2023-01-23 14:21:49.964740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2068f7bfe134'
down_revision = '561bf9dd5f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spr_volume_degree_zet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_standard', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spr_volume_degree_zet', schema=None) as batch_op:
        batch_op.drop_column('id_standard')

    # ### end Alembic commands ###
