"""add program_code fk to SprVolumeDegreeZET

Revision ID: 2257b1b538a1
Revises: 2068f7bfe134
Create Date: 2023-01-23 14:23:33.257058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2257b1b538a1'
down_revision = '2068f7bfe134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spr_volume_degree_zet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_code', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('id_standard', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'spr_okco', ['program_code'], ['program_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spr_volume_degree_zet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_standard')
        batch_op.drop_column('program_code')

    # ### end Alembic commands ###
