"""add lk_id

Revision ID: 279b2bb08dd1
Revises: 13b01ad90cd2
Create Date: 2024-06-01 22:09:48.805492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279b2bb08dd1'
down_revision = '13b01ad90cd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_22', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_21', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')

    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lk_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_column('lk_id')

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_21', 'd_modules', ['id_module'], ['id'])
        batch_op.create_foreign_key('aup_data_ibfk_22', 'groups', ['id_group'], ['id_group'])

    # ### end Alembic commands ###
