"""add AUP_DATA

Revision ID: 28b86680b406
Revises: a1ddb03a9239
Create Date: 2023-01-30 02:09:11.175257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b86680b406'
down_revision = 'a1ddb03a9239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aup_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('shifr', sa.String(length=30), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.String(length=50), nullable=False),
    sa.Column('period_control_id', sa.Integer(), nullable=False),
    sa.Column('type_control_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('measure', sa.Integer(), nullable=False),
    sa.Column('zet', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aup_data')
    # ### end Alembic commands ###
