"""Add color to module model

Revision ID: 296abf307e69
Revises: d4b1b8702797
Create Date: 2024-05-06 23:01:46.987041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296abf307e69'
down_revision = 'd4b1b8702797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('d_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=8), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('d_modules', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
