"""add approved field for users

Revision ID: 2de9c4bdc2ca
Revises: 8813d9da8065
Create Date: 2024-05-23 01:40:11.366790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de9c4bdc2ca'
down_revision = '8813d9da8065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_lk', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_column('approved_lk')

    # ### end Alembic commands ###
