"""empty message

Revision ID: 3254dc47f198
Revises: c8fdcf15c4e7
Create Date: 2024-05-27 00:13:47.772566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3254dc47f198'
down_revision = 'c8fdcf15c4e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ChangeLog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_18', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_19', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_19', 'd_modules', ['id_module'], ['id'])
        batch_op.create_foreign_key('aup_data_ibfk_18', 'groups', ['id_group'], ['id_group'])

    with op.batch_alter_table('ChangeLog', schema=None) as batch_op:
        batch_op.drop_column('row_id')

    # ### end Alembic commands ###
