"""alter unification_load table

Revision ID: 3347eedd112e
Revises: c03a49c2b8e4
Create Date: 2024-03-26 03:00:22.742875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3347eedd112e'
down_revision = 'c03a49c2b8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unification_load', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discipline_period_assoc_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'discipline_period_assoc', ['discipline_period_assoc_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unification_load', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('discipline_period_assoc_id')

    # ### end Alembic commands ###
