"""change workload columns

Revision ID: 39393e9b4964
Revises: 66ebbd29e059
Create Date: 2022-09-30 15:29:53.224639

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39393e9b4964'
down_revision = '66ebbd29e059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workload')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workload',
    sa.Column('id_workload', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cypher', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('part', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('id_module', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_aup', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('record_type', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('discipline', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('period', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('load', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('measurement', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('zet', mysql.FLOAT(), nullable=False),
    sa.Column('block', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_aup'], ['tbl_aup.id_aup'], name='fk_workload_id_aup_tbl_aup', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_module'], ['tbl_module.id_module'], name='fk_workload_id_module_tbl_module'),
    sa.PrimaryKeyConstraint('id_workload'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
