"""remove study group id from gradetable

Revision ID: 3b17cac5d4a0
Revises: 73dca8d36729
Create Date: 2024-05-15 20:49:00.146479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b17cac5d4a0'
down_revision = '73dca8d36729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_table', schema=None) as batch_op:
        batch_op.drop_constraint('grade_table_ibfk_3', type_='foreignkey')
        batch_op.drop_column('study_group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_group_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('grade_table_ibfk_3', 'study_group', ['study_group_id'], ['id'])

    # ### end Alembic commands ###
