"""Add cascade delete to AUP foreign keys in tbl_aup

Revision ID: 3bc29a7191bd
Revises: 5777d369be4d
Create Date: 2025-04-26 17:41:08.053768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc29a7191bd'
down_revision = '5777d369be4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_aup', schema=None) as batch_op:
        batch_op.drop_constraint('tbl_aup_ibfk_5', type_='foreignkey')
        batch_op.drop_constraint('tbl_aup_ibfk_6', type_='foreignkey')
        batch_op.create_foreign_key(None, 'spr_rop', ['id_rop'], ['id_rop'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'spr_name_op', ['id_spec'], ['id_spec'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_aup', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tbl_aup_ibfk_6', 'spr_name_op', ['id_spec'], ['id_spec'], ondelete='SET NULL')
        batch_op.create_foreign_key('tbl_aup_ibfk_5', 'spr_rop', ['id_rop'], ['id_rop'])

    # ### end Alembic commands ###
