"""change unification load model

Revision ID: 3ee9538205d1
Revises: a2ec0c4133d9
Create Date: 2023-09-28 13:36:20.197841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee9538205d1'
down_revision = 'a2ec0c4133d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unification_load',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unification_id', sa.Integer(), nullable=False),
    sa.Column('control_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['control_type_id'], ['d_control_type.id'], ),
    sa.ForeignKeyConstraint(['unification_id'], ['unification.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unification_load')
    # ### end Alembic commands ###
