"""add is_delete and date_delete to AupInfo

Revision ID: 41b4134f7370
Revises: 93e96b28aede
Create Date: 2025-04-26 08:45:03.267771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41b4134f7370'
down_revision = '93e96b28aede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_type_short_name',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('control_type_id', sa.Integer(), nullable=False),
    sa.Column('shortname', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['control_type_id'], ['d_control_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'control_type_id')
    )
    op.create_table('weeks',
    sa.Column('aup_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aup_id'], ['tbl_aup.id_aup'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['d_period.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('aup_id', 'period_id')
    )
    with op.batch_alter_table('Revision', schema=None) as batch_op:
        batch_op.drop_constraint('Revision_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tbl_aup', ['aup_id'], ['id_aup'], ondelete='CASCADE')

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_for_report', sa.Boolean(), nullable=True))

    with op.batch_alter_table('d_control_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_shortname', sa.String(length=255), nullable=True))
        batch_op.drop_column('shortname')

    with op.batch_alter_table('tbl_aup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_delete', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('date_delete', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['num_aup'])

    with op.batch_alter_table('tbl_department', schema=None) as batch_op:
        batch_op.drop_constraint('tbl_department_ibfk_1', type_='foreignkey')
        batch_op.drop_column('faculty_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_department', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tbl_department_ibfk_1', 'spr_faculty', ['faculty_id'], ['id_faculty'])

    with op.batch_alter_table('tbl_aup', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('date_delete')
        batch_op.drop_column('is_delete')

    with op.batch_alter_table('d_control_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shortname', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('default_shortname')

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_column('used_for_report')

    with op.batch_alter_table('Revision', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Revision_ibfk_1', 'tbl_aup', ['aup_id'], ['id_aup'])

    op.drop_table('weeks')
    op.drop_table('control_type_short_name')
    # ### end Alembic commands ###
