"""grade type small fixes

Revision ID: 44b5a167b575
Revises: c3f8dc1a763d
Create Date: 2024-05-16 01:56:27.380725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44b5a167b575'
down_revision = 'c3f8dc1a763d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), nullable=False))
        batch_op.alter_column('min_grade',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('max_grade',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_type', schema=None) as batch_op:
        batch_op.alter_column('max_grade',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('min_grade',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
