"""change rule relation to real_okso

Revision ID: 45887e03d2a3
Revises: 92313dba8fc0
Create Date: 2023-08-01 19:47:07.849257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45887e03d2a3'
down_revision = '92313dba8fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aup_info_has_rule',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('realized_okso_id', sa.Integer(), nullable=False),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('ed_izmereniya_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ed_izmereniya_id'], ['d_ed_izmereniya.id'], ),
    sa.ForeignKeyConstraint(['realized_okso_id'], ['tbl_realized_okso.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['tbl_rule.id'], ),
    sa.PrimaryKeyConstraint('rule_id', 'realized_okso_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aup_info_has_rule')
    # ### end Alembic commands ###
