"""add request_approve_date

Revision ID: 4693e09346f8
Revises: 2de9c4bdc2ca
Create Date: 2024-05-27 00:39:10.902066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4693e09346f8'
down_revision = '2de9c4bdc2ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_approve_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_column('request_approve_date')

    # ### end Alembic commands ###
