"""indicator storage

Revision ID: 4730cda46a2c
Revises: 632afbb23f5a
Create Date: 2025-06-02 14:51:26.235705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4730cda46a2c'
down_revision = '632afbb23f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competencies_indicator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_ps_elements_ids', sa.JSON(), nullable=True, comment='JSON массив ID выбранных элементов ПС (ТД, НУ, НЗ), на основе которых сформирован индикатор'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competencies_indicator', schema=None) as batch_op:
        batch_op.drop_column('selected_ps_elements_ids')

    # ### end Alembic commands ###
