"""add grouping to worklod and add table tbl_group

Revision ID: 477fb28b4137
Revises: 6afe0fe4a65d
Create Date: 2022-11-19 10:31:36.988697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477fb28b4137'
down_revision = '6afe0fe4a65d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_group',
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('name_group', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_group')
    )
    op.drop_constraint('spr_volume_degree_zet_ibfk_2', 'spr_volume_degree_zet', type_='foreignkey')
    op.add_column('workload', sa.Column('id_group', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'workload', 'tbl_group', ['id_group'], ['id_group'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workload', type_='foreignkey')
    op.drop_column('workload', 'id_group')
    op.create_foreign_key('spr_volume_degree_zet_ibfk_2', 'spr_volume_degree_zet', 'spr_standard_zet', ['id_standard'], ['id_standard'])
    op.drop_table('tbl_group')
    # ### end Alembic commands ###
