"""Create mode table

Revision ID: 4882e927798f
Revises: 189e31699121
Create Date: 2024-03-17 20:33:37.685569

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4882e927798f'
down_revision = '189e31699121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Mode',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('action', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('Permissions',
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('mode_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['mode_id'], ['Mode.id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id_role'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Permissions')
    op.drop_table('Mode')
    # ### end Alembic commands ###
