"""unification tables

Revision ID: 4c0bcf003b16
Revises: a309d8cdcaea
Create Date: 2024-03-24 01:18:00.566601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c0bcf003b16'
down_revision = 'a309d8cdcaea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unification_discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zet', sa.Float(), nullable=True),
    sa.Column('discipline', sa.String(length=255), nullable=True),
    sa.Column('is_faculties_different', sa.Boolean(), nullable=True),
    sa.Column('ugsn', sa.String(length=255), nullable=True),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discipline_period_assoc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unification_discipline_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['d_period.id'], ),
    sa.ForeignKeyConstraint(['unification_discipline_id'], ['unification_discipline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unification_load',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lectures', sa.Float(), nullable=True),
    sa.Column('srs', sa.Float(), nullable=True),
    sa.Column('practices', sa.Float(), nullable=True),
    sa.Column('control_type_id', sa.Integer(), nullable=True),
    sa.Column('zet', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['control_type_id'], ['d_control_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculty_discipline_period',
    sa.Column('discipline_period_id', sa.Integer(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_period_id'], ['discipline_period_assoc.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['spr_faculty.id_faculty'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faculty_discipline_period')
    op.drop_table('unification_load')
    op.drop_table('discipline_period_assoc')
    op.drop_table('unification_discipline')
    # ### end Alembic commands ###
