"""delete group

Revision ID: 50aa103432a5
Revises: a896a9f55d01
Create Date: 2023-03-19 21:35:52.845821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50aa103432a5'
down_revision = 'a896a9f55d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_index('aup_data_ibfk_10')
        batch_op.drop_constraint('aup_data_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_4', 'groups', ['id_group'], ['id_group'])
        batch_op.create_index('aup_data_ibfk_10', ['id_period'], unique=False)

    # ### end Alembic commands ###
