"""fix grade table

Revision ID: 554f4b9f1eaf
Revises: 936e2e97bfc8
Create Date: 2024-05-15 22:05:31.633239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554f4b9f1eaf'
down_revision = '936e2e97bfc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('study_group_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'study_group', ['study_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('study_group_id')

    # ### end Alembic commands ###
