"""cascade delete grade type

Revision ID: 55960b6b2786
Revises: 1c5d78dfcfbe
Create Date: 2024-06-09 19:07:39.488702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55960b6b2786'
down_revision = '1c5d78dfcfbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_21', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_22', type_='foreignkey')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')

    with op.batch_alter_table('grade_column', schema=None) as batch_op:
        batch_op.drop_constraint('grade_column_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'grade_type', ['grade_type_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('grades_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'grade_column', ['grade_column_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grades_ibfk_2', 'grade_column', ['grade_column_id'], ['id'])

    with op.batch_alter_table('grade_column', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grade_column_ibfk_3', 'grade_type', ['grade_type_id'], ['id'])

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_22', 'groups', ['id_group'], ['id_group'])
        batch_op.create_foreign_key('aup_data_ibfk_21', 'd_modules', ['id_module'], ['id'])

    # ### end Alembic commands ###
