"""add program_code fk to SprVolumeDegreeZET

Revision ID: 561bf9dd5f91
Revises: 254daa6f4ec5
Create Date: 2023-01-23 14:21:24.804071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '561bf9dd5f91'
down_revision = '254daa6f4ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spr_volume_degree_zet', schema=None) as batch_op:
        batch_op.drop_column('id_standard')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spr_volume_degree_zet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_standard', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
