"""Add cascade delete to AUP related tables

Revision ID: 5777d369be4d
Revises: 41b4134f7370
Create Date: 2025-04-26 17:26:37.306741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5777d369be4d'
down_revision = '41b4134f7370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competencies_educational_program_aup', schema=None) as batch_op:
        batch_op.drop_constraint('competencies_educational_program_aup_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tbl_aup', ['aup_id'], ['id_aup'], ondelete='CASCADE')

    with op.batch_alter_table('competencies_matrix', schema=None) as batch_op:
        batch_op.drop_constraint('competencies_matrix_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'aup_data', ['aup_data_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('discipline_table', schema=None) as batch_op:
        batch_op.drop_constraint('discipline_table_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tbl_aup', ['id_aup'], ['id_aup'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discipline_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('discipline_table_ibfk_1', 'tbl_aup', ['id_aup'], ['id_aup'])

    with op.batch_alter_table('competencies_matrix', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('competencies_matrix_ibfk_1', 'aup_data', ['aup_data_id'], ['id'])

    with op.batch_alter_table('competencies_educational_program_aup', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('competencies_educational_program_aup_ibfk_1', 'tbl_aup', ['aup_id'], ['id_aup'])

    # ### end Alembic commands ###
