"""add user_agent field to token model

Revision ID: 584667013c24
Revises: 1d7b37ac97ca
Create Date: 2023-09-24 12:58:25.000927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584667013c24'
down_revision = '1d7b37ac97ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('name_role', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_role')
    )
    op.create_table('tbl_users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_role'], ['roles.id_role'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('password_hash')
    )
    op.create_table('tbl_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=256), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_faculty',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['spr_faculty.id_faculty'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id_user'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_faculty')
    op.drop_table('tbl_token')
    op.drop_table('tbl_users')
    op.drop_table('roles')
    # ### end Alembic commands ###
