"""alter unification_discipline table

Revision ID: 5c44bb549e9b
Revises: bd99016f646c
Create Date: 2024-03-26 03:48:14.823968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c44bb549e9b'
down_revision = 'bd99016f646c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unification_okso_assoc',
    sa.Column('unification_id', sa.Integer(), nullable=True),
    sa.Column('okso_id', sa.String(length=255, collation='utf8mb4_unicode_ci'), nullable=True),
    sa.ForeignKeyConstraint(['okso_id'], ['spr_okco.program_code'], ),
    sa.ForeignKeyConstraint(['unification_id'], ['unification_discipline.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unification_okso_assoc')
    # ### end Alembic commands ###
