"""add rpd tables

Revision ID: 5c9dce78a6fe
Revises: 711c0a611d52
Create Date: 2024-03-20 03:17:43.372833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9dce78a6fe'
down_revision = '711c0a611d52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spr_discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aup', sa.Integer(), nullable=False),
    sa.Column('id_unique_discipline', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aup'], ['tbl_aup.id_aup'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_unique_discipline'], ['spr_discipline.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=400), nullable=True),
    sa.Column('chapter', sa.String(length=400), nullable=True),
    sa.Column('id_type_control', sa.Integer(), nullable=True),
    sa.Column('task_link', sa.String(length=400), nullable=True),
    sa.Column('id_rpd', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_rpd'], ['rpd.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_type_control'], ['d_control_type.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic')
    op.drop_table('rpd')
    op.drop_table('spr_discipline')
    # ### end Alembic commands ###
