"""alter Users table

Revision ID: 5cc30f446f5d
Revises: 803722f2c4e4
Create Date: 2024-03-11 21:58:26.402814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cc30f446f5d'
down_revision = '803722f2c4e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_constraint('tbl_users_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('tbl_users_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['id_role'], ['id_role'])
        batch_op.create_foreign_key(None, 'tbl_department', ['department_id'], ['id_department'])

    with op.batch_alter_table('users_faculty', schema=None) as batch_op:
        batch_op.drop_constraint('users_faculty_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('users_faculty_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'spr_faculty', ['faculty_id'], ['id_faculty'])
        batch_op.create_foreign_key(None, 'tbl_users', ['user_id'], ['id_user'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_faculty', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_faculty_ibfk_2', 'tbl_users', ['user_id'], ['id_user'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('users_faculty_ibfk_1', 'spr_faculty', ['faculty_id'], ['id_faculty'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tbl_users_ibfk_2', 'tbl_department', ['department_id'], ['id_department'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('tbl_users_ibfk_1', 'roles', ['id_role'], ['id_role'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###
