"""add cascades

Revision ID: 5ccd0bb4559a
Revises: 4693e09346f8
Create Date: 2024-05-27 04:03:46.250370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ccd0bb4559a'
down_revision = '4693e09346f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint('permissions_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('permissions_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id_role'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'mode', ['mode_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tbl_token', schema=None) as batch_op:
        batch_op.drop_constraint('tbl_token_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tbl_users', ['user_id'], ['id_user'], ondelete='CASCADE')

    with op.batch_alter_table('user_has_role', schema=None) as batch_op:
        batch_op.drop_constraint('user_has_role_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('user_has_role_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id_role'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tbl_users', ['user_id'], ['id_user'], ondelete='CASCADE')

    with op.batch_alter_table('users_faculty', schema=None) as batch_op:
        batch_op.drop_constraint('users_faculty_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('users_faculty_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'spr_faculty', ['faculty_id'], ['id_faculty'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tbl_users', ['user_id'], ['id_user'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_faculty', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('users_faculty_ibfk_2', 'tbl_users', ['user_id'], ['id_user'])
        batch_op.create_foreign_key('users_faculty_ibfk_1', 'spr_faculty', ['faculty_id'], ['id_faculty'])

    with op.batch_alter_table('user_has_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_has_role_ibfk_1', 'roles', ['role_id'], ['id_role'])
        batch_op.create_foreign_key('user_has_role_ibfk_2', 'tbl_users', ['user_id'], ['id_user'])

    with op.batch_alter_table('tbl_token', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tbl_token_ibfk_1', 'tbl_users', ['user_id'], ['id_user'])

    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('permissions_ibfk_2', 'roles', ['role_id'], ['id_role'])
        batch_op.create_foreign_key('permissions_ibfk_1', 'mode', ['mode_id'], ['id'])

    # ### end Alembic commands ###
