"""del models and some fix

Revision ID: 5d5a9799211c
Revises: 45b079874e82
Create Date: 2023-01-18 00:44:55.261420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d5a9799211c'
down_revision = '45b079874e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_map', schema=None) as batch_op:
        batch_op.drop_column('id_module')

    with op.batch_alter_table('workload', schema=None) as batch_op:
        batch_op.drop_constraint('workload_ibfk_2', type_='foreignkey')
        batch_op.drop_column('id_module')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_module', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('workload_ibfk_2', 'tbl_module', ['id_module'], ['id_module'])

    with op.batch_alter_table('work_map', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_module', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
