"""add mtm unification realized okso realation

Revision ID: 5dd54f677754
Revises: b6e83b182817
Create Date: 2023-09-27 21:06:39.573925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5dd54f677754'
down_revision = 'b6e83b182817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unification_realized_okso',
    sa.Column('unification_id', sa.Integer(), nullable=True),
    sa.Column('realized_okso_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['realized_okso_id'], ['tbl_realized_okso.id'], ),
    sa.ForeignKeyConstraint(['unification_id'], ['unification.id'], )
    )
    with op.batch_alter_table('unification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_education_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('unification_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'spr_form_education', ['form_education_id'], ['id_form'])
        batch_op.drop_column('form_education')
        batch_op.drop_column('program_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_code', mysql.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('form_education', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('unification_ibfk_2', 'spr_form_education', ['form_education'], ['id_form'])
        batch_op.drop_column('form_education_id')

    op.drop_table('unification_realized_okso')
    # ### end Alembic commands ###
