"""alter aup_data

Revision ID: 5e1b5a316f86
Revises: 5c9dce78a6fe
Create Date: 2024-03-20 03:29:08.443654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e1b5a316f86'
down_revision = '5c9dce78a6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_discipline', sa.String(length=350), nullable=False))
        batch_op.add_column(sa.Column('id_discipline', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'spr_discipline', ['id_discipline'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('discipline')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discipline', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=350), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_discipline')
        batch_op.drop_column('_discipline')

    # ### end Alembic commands ###
