"""custom grade_type

Revision ID: 5e6e1bc2529e
Revises: f0ef1c67cbff
Create Date: 2024-06-09 18:58:47.699012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e6e1bc2529e'
down_revision = 'f0ef1c67cbff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_22', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_21', type_='foreignkey')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')

    with op.batch_alter_table('grade_column', schema=None) as batch_op:
        batch_op.alter_column('is_custom',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_column', schema=None) as batch_op:
        batch_op.alter_column('is_custom',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_21', 'groups', ['id_group'], ['id_group'])
        batch_op.create_foreign_key('aup_data_ibfk_22', 'd_modules', ['id_module'], ['id'])

    # ### end Alembic commands ###
