"""alter unification laod

Revision ID: 60304ed0a78b
Revises: 4c0bcf003b16
Create Date: 2024-03-24 01:58:25.528602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60304ed0a78b'
down_revision = '4c0bcf003b16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unification_load', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education_form_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'spr_form_education', ['education_form_id'], ['id_form'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unification_load', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('education_form_id')

    # ### end Alembic commands ###
