"""refactor_ps_parsing_models

Revision ID: 609072b33446
Revises: a0c586ca251a
Create Date: 2025-05-21 17:36:28.593495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '609072b33446'
down_revision = 'a0c586ca251a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competencies_prof_standard', schema=None) as batch_op:
        batch_op.drop_column('parsed_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competencies_prof_standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parsed_content', mysql.TEXT(), nullable=True, comment='Содержимое стандарта в Markdown'))

    # ### end Alembic commands ###
