"""empty message

Revision ID: 628b4602934d
Revises: b53ed842fc5f
Create Date: 2023-02-16 16:41:01.001494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '628b4602934d'
down_revision = 'b53ed842fc5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'd_part', ['id_part'], ['id_part'])
        batch_op.create_foreign_key(None, 'd_type_record', ['id_type_record'], ['id_type_record'])
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id_module'])
        batch_op.create_foreign_key(None, 'd_period', ['id_period'], ['id_period'])
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'])
        batch_op.create_foreign_key(None, 'd_blocks', ['id_block'], ['id_block'])
        batch_op.create_foreign_key(None, 'd_control_type', ['id_type_control'], ['id_type_control'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
