"""added missing PS f fields

Revision ID: 632afbb23f5a
Revises: 87d13b09e467
Create Date: 2025-06-02 08:18:41.255831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632afbb23f5a'
down_revision = '87d13b09e467'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competencies_prof_standard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_area_name', sa.String(length=500), nullable=True, comment='Наименование вида профессиональной деятельности'))
        batch_op.add_column(sa.Column('activity_purpose', sa.Text(), nullable=True, comment='Основная цель вида профессиональной деятельности'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competencies_prof_standard', schema=None) as batch_op:
        batch_op.drop_column('activity_purpose')
        batch_op.drop_column('activity_area_name')

    # ### end Alembic commands ###
