"""Add SerializationMixin to AupInfo and update nullable/ondelete in tbl_aup

Revision ID: 64cc0b7d4252
Revises: 3bc29a7191bd
Create Date: 2025-05-11 16:55:25.388010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64cc0b7d4252'
down_revision = '3bc29a7191bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spr_name_op', schema=None) as batch_op:
        batch_op.alter_column('num_profile',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('tbl_aup', schema=None) as batch_op:
        batch_op.alter_column('file',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('base',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('id_rop',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('type_educ',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('qualification',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('type_standard',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('period_educ',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('years',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_spec',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('year_end',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_aup', schema=None) as batch_op:
        batch_op.alter_column('year_end',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_spec',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('years',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('period_educ',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('type_standard',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('qualification',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('type_educ',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('id_rop',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('base',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('file',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('spr_name_op', schema=None) as batch_op:
        batch_op.alter_column('num_profile',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
