"""add id_aup

Revision ID: 650eb39725c3
Revises: ac8e5615ca63
Create Date: 2023-02-07 01:40:43.798765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650eb39725c3'
down_revision = 'ac8e5615ca63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('work_map_ibfk_1', 'work_map', type_='foreignkey')
    op.create_foreign_key(None, 'work_map', 'tbl_aup', ['id_aup'], ['id_aup'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_map', type_='foreignkey')
    op.create_foreign_key('work_map_ibfk_1', 'work_map', 'tbl_aup', ['id_aup'], ['id_aup'])
    # ### end Alembic commands ###
