"""Initial commit.

Revision ID: 66ebbd29e059
Revises: 
Create Date: 2022-09-29 03:05:44.958445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ebbd29e059'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spr_branch',
    sa.Column('id_branch', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_branch', name=op.f('pk_spr_branch'))
    )
    op.create_table('spr_degree_education',
    sa.Column('id_degree', sa.Integer(), nullable=False),
    sa.Column('name_deg', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_degree', name=op.f('pk_spr_degree_education'))
    )
    op.create_table('spr_form_education',
    sa.Column('id_form', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_form', name=op.f('pk_spr_form_education'))
    )
    op.create_table('spr_okco',
    sa.Column('program_code', sa.String(length=255), nullable=False),
    sa.Column('name_okco', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('program_code', name=op.f('pk_spr_okco'))
    )
    op.create_table('spr_rop',
    sa.Column('id_rop', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('middle_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_rop', name=op.f('pk_spr_rop'))
    )
    op.create_table('tbl_module',
    sa.Column('id_module', sa.Integer(), nullable=False),
    sa.Column('name_module', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_module', name=op.f('pk_tbl_module'))
    )
    op.create_table('spr_faculty',
    sa.Column('id_faculty', sa.Integer(), nullable=False),
    sa.Column('name_faculty', sa.String(length=255), nullable=False),
    sa.Column('id_branch', sa.Integer(), nullable=False),
    sa.Column('dean', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_branch'], ['spr_branch.id_branch'], name=op.f('fk_spr_faculty_id_branch_spr_branch')),
    sa.PrimaryKeyConstraint('id_faculty', name=op.f('pk_spr_faculty'))
    )
    op.create_table('spr_name_op',
    sa.Column('id_spec', sa.Integer(), nullable=False),
    sa.Column('program_code', sa.String(length=255), nullable=False),
    sa.Column('num_profile', sa.String(length=255), nullable=False),
    sa.Column('name_spec', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['program_code'], ['spr_okco.program_code'], name=op.f('fk_spr_name_op_program_code_spr_okco')),
    sa.PrimaryKeyConstraint('id_spec', name=op.f('pk_spr_name_op'))
    )
    op.create_table('tbl_duration_edu',
    sa.Column('id_duration', sa.Integer(), nullable=False),
    sa.Column('id_degree', sa.Integer(), nullable=False),
    sa.Column('id_form', sa.Integer(), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('id_spec', sa.Integer(), nullable=False),
    sa.Column('year_beg', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_degree'], ['spr_degree_education.id_degree'], name=op.f('fk_tbl_duration_edu_id_degree_spr_degree_education')),
    sa.ForeignKeyConstraint(['id_form'], ['spr_form_education.id_form'], name=op.f('fk_tbl_duration_edu_id_form_spr_form_education')),
    sa.ForeignKeyConstraint(['id_spec'], ['spr_name_op.id_spec'], name=op.f('fk_tbl_duration_edu_id_spec_spr_name_op')),
    sa.PrimaryKeyConstraint('id_duration', name=op.f('pk_tbl_duration_edu'))
    )
    op.create_table('tbl_op',
    sa.Column('id_op', sa.Integer(), nullable=False),
    sa.Column('id_duration', sa.Integer(), nullable=False),
    sa.Column('id_faculty', sa.Integer(), nullable=False),
    sa.Column('id_rop', sa.Integer(), nullable=False),
    sa.Column('type_educ', sa.String(length=255), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=False),
    sa.Column('type_standard', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('period_educ', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_duration'], ['tbl_duration_edu.id_duration'], name=op.f('fk_tbl_op_id_duration_tbl_duration_edu')),
    sa.ForeignKeyConstraint(['id_faculty'], ['spr_faculty.id_faculty'], name=op.f('fk_tbl_op_id_faculty_spr_faculty')),
    sa.ForeignKeyConstraint(['id_rop'], ['spr_rop.id_rop'], name=op.f('fk_tbl_op_id_rop_spr_rop')),
    sa.PrimaryKeyConstraint('id_op', name=op.f('pk_tbl_op'))
    )
    op.create_table('tbl_aup',
    sa.Column('id_aup', sa.Integer(), nullable=False),
    sa.Column('id_op', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('num_aup', sa.String(length=255), nullable=False),
    sa.Column('base', sa.String(length=255), nullable=False),
    sa.Column('fso', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_op'], ['tbl_op.id_op'], name=op.f('fk_tbl_aup_id_op_tbl_op'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_aup', name=op.f('pk_tbl_aup'))
    )
    op.create_table('workload',
    sa.Column('id_workload', sa.Integer(), nullable=False),
    sa.Column('cypher', sa.String(length=255), nullable=False),
    sa.Column('part', sa.String(length=255), nullable=False),
    sa.Column('id_module', sa.Integer(), nullable=False),
    sa.Column('id_aup', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=255), nullable=False),
    sa.Column('discipline', sa.String(length=255), nullable=False),
    sa.Column('period', sa.String(length=255), nullable=False),
    sa.Column('load', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('measurement', sa.String(length=255), nullable=False),
    sa.Column('zet', sa.Float(), nullable=False),
    sa.Column('block', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_aup'], ['tbl_aup.id_aup'], name=op.f('fk_workload_id_aup_tbl_aup'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_module'], ['tbl_module.id_module'], name=op.f('fk_workload_id_module_tbl_module')),
    sa.PrimaryKeyConstraint('id_workload', name=op.f('pk_workload'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workload')
    op.drop_table('tbl_aup')
    op.drop_table('tbl_op')
    op.drop_table('tbl_duration_edu')
    op.drop_table('spr_name_op')
    op.drop_table('spr_faculty')
    op.drop_table('tbl_module')
    op.drop_table('spr_rop')
    op.drop_table('spr_okco')
    op.drop_table('spr_form_education')
    op.drop_table('spr_degree_education')
    op.drop_table('spr_branch')
    # ### end Alembic commands ###
