"""add discipline table

Revision ID: 67ac7e17a6d2
Revises: 49c554bed3d8
Create Date: 2024-05-30 16:59:11.564958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67ac7e17a6d2'
down_revision = '49c554bed3d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipline_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aup', sa.Integer(), nullable=False),
    sa.Column('id_unique_discipline', sa.Integer(), nullable=False),
    sa.Column('study_group_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aup'], ['tbl_aup.id_aup'], ),
    sa.ForeignKeyConstraint(['id_unique_discipline'], ['spr_discipline.id'], ),
    sa.ForeignKeyConstraint(['study_group_id'], ['study_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_21', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_22', type_='foreignkey')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')

    with op.batch_alter_table('grade_column', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discipline_table_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('grade_column_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'discipline_table', ['discipline_table_id'], ['id'])
        batch_op.drop_column('grade_table_id')

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discipline_table_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('topic_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'discipline_table', ['discipline_table_id'], ['id'])
        batch_op.drop_column('semester')
        batch_op.drop_column('id_rpd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_rpd', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('semester', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('topic_ibfk_1', 'rpd', ['id_rpd'], ['id'])
        batch_op.drop_column('discipline_table_id')

    with op.batch_alter_table('grade_column', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_table_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grade_column_ibfk_2', 'grade_table', ['grade_table_id'], ['id'])
        batch_op.drop_column('discipline_table_id')

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_22', 'd_modules', ['id_module'], ['id'])
        batch_op.create_foreign_key('aup_data_ibfk_21', 'groups', ['id_group'], ['id_group'])

    op.drop_table('discipline_table')
    # ### end Alembic commands ###
