"""add topic id for column grade

Revision ID: 696dfcfb549a
Revises: eb83e4cb9b6f
Create Date: 2024-05-19 22:36:37.712245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696dfcfb549a'
down_revision = 'eb83e4cb9b6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_column', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_column', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('topic_id')

    # ### end Alembic commands ###
