"""old stable ver

Revision ID: 6a19894040ee
Revises: f399baa8dbcf
Create Date: 2023-01-21 22:13:53.260357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a19894040ee'
down_revision = 'f399baa8dbcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workload', 'id_module',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'workload', 'tbl_module', ['id_module'], ['id_module'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workload', type_='foreignkey')
    op.alter_column('workload', 'id_module',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
