"""Create weeks table

Revision ID: 6a5070535e5b
Revises: a67d0392a2dc
Create Date: 2024-10-20 18:28:53.864763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a5070535e5b'
down_revision = 'a67d0392a2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weeks',
    sa.Column('aup_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aup_id'], ['tbl_aup.id_aup'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['d_period.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('aup_id', 'period_id')
    )
    with op.batch_alter_table('Revision', schema=None) as batch_op:
        batch_op.drop_constraint('Revision_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tbl_aup', ['aup_id'], ['id_aup'], ondelete='CASCADE')

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_20', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_21', type_='foreignkey')
        batch_op.drop_index('aup_data_ibfk_19')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'])
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_21', 'groups', ['id_group'], ['id_group'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key('aup_data_ibfk_20', 'd_modules', ['id_module'], ['id'], onupdate='RESTRICT', ondelete='SET NULL')
        batch_op.create_index('aup_data_ibfk_19', ['id_group'], unique=False)

    with op.batch_alter_table('Revision', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Revision_ibfk_1', 'tbl_aup', ['aup_id'], ['id_aup'], onupdate='RESTRICT', ondelete='CASCADE')

    op.drop_table('weeks')
    # ### end Alembic commands ###
