"""empty message

Revision ID: 6a9f8e562b46
Revises: db04632784dc
Create Date: 2022-10-31 21:16:08.887009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a9f8e562b46'
down_revision = 'db04632784dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'spr_volume_degree_zet', 'spr_standard_zet', ['id_standard'], ['id_standard'])
    op.drop_column('spr_volume_degree_zet', 'year_of_start')
    op.drop_column('spr_volume_degree_zet', 'type_standard')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spr_volume_degree_zet', sa.Column('type_standard', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('spr_volume_degree_zet', sa.Column('year_of_start', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'spr_volume_degree_zet', type_='foreignkey')
    # ### end Alembic commands ###
