"""add foraign key for spr_volume_degree_zet.id_standard

Revision ID: 6afe0fe4a65d
Revises: d5ffc75c92b8
Create Date: 2022-11-08 00:37:36.719346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6afe0fe4a65d'
down_revision = 'd5ffc75c92b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'spr_volume_degree_zet', 'spr_standard_zet', ['id_standard'], ['id_standard'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spr_volume_degree_zet', type_='foreignkey')
    # ### end Alembic commands ###
