"""add weight grade

Revision ID: 6c5cf34f34fd
Revises: 7be95e905513
Create Date: 2024-05-20 01:48:24.431114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5cf34f34fd'
down_revision = '7be95e905513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_grade', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_type', schema=None) as batch_op:
        batch_op.drop_column('weight_grade')

    # ### end Alembic commands ###
