"""empty message

Revision ID: 711c0a611d52
Revises: 6646b414b766
Create Date: 2024-03-20 03:11:39.857150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711c0a611d52'
down_revision = '6646b414b766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('mode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mode_id'], ['mode.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id_role'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    op.drop_table('mode')
    # ### end Alembic commands ###
