"""rename sprgrade

Revision ID: 73dca8d36729
Revises: 8b8cc89e3711
Create Date: 2024-05-15 20:18:41.950192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73dca8d36729'
down_revision = '8b8cc89e3711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spr_grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('grade_table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_table_id'], ['grade_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sprgrade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sprgrade',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('grade_table_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['grade_table_id'], ['grade_table.id'], name='sprgrade_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('spr_grade')
    # ### end Alembic commands ###
