"""fix work_maps

Revision ID: 758889d95669
Revises: d0fc3fc06852
Create Date: 2022-12-13 00:38:34.658406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758889d95669'
down_revision = 'd0fc3fc06852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_group', sa.Column('color', sa.String(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_group', 'color')
    # ### end Alembic commands ###
