"""aupdata.id_group ondelete

Revision ID: 7619a97a3322
Revises: ea196d56c74f
Create Date: 2024-05-26 23:34:07.062413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7619a97a3322'
down_revision = 'ea196d56c74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ChangeLog', schema=None) as batch_op:
        batch_op.drop_constraint('ChangeLog_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Revision', ['revision_id'], ['id'])
        batch_op.drop_column('row_id')

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_9', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_18', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_18', 'groups', ['id_group'], ['id_group'])
        batch_op.create_foreign_key('aup_data_ibfk_9', 'd_modules', ['id_module'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('ChangeLog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ChangeLog_ibfk_1', 'Revision', ['revision_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
