"""add date_task_finish_include

Revision ID: 77d003f1888d
Revises: 6c5cf34f34fd
Create Date: 2024-05-21 17:56:08.824592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d003f1888d'
down_revision = '6c5cf34f34fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_task_finish_include', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_column('date_task_finish_include')

    # ### end Alembic commands ###
