"""add semester in grade table

Revision ID: 7aa9023c106c
Revises: 696dfcfb549a
Create Date: 2024-05-19 22:54:24.510278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa9023c106c'
down_revision = '696dfcfb549a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_table', schema=None) as batch_op:
        batch_op.drop_column('semester')

    # ### end Alembic commands ###
