"""add binary grade

Revision ID: 7be95e905513
Revises: b576627d4a2c
Create Date: 2024-05-20 01:35:16.631749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be95e905513'
down_revision = 'b576627d4a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('binary', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_type', schema=None) as batch_op:
        batch_op.drop_column('binary')

    # ### end Alembic commands ###
