"""fix grade column

Revision ID: 7f7703c41901
Revises: 554f4b9f1eaf
Create Date: 2024-05-15 22:36:14.270263

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f7703c41901'
down_revision = '554f4b9f1eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('type_grade')
    with op.batch_alter_table('grade_column', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_type_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('grade_column_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'grade_type', ['grade_type_id'], ['id'])
        batch_op.drop_column('type_grade_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_column', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_grade_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grade_column_ibfk_2', 'type_grade', ['type_grade_id'], ['id'])
        batch_op.drop_column('grade_type_id')

    op.create_table('type_grade',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('grade_type')
    # ### end Alembic commands ###
