"""add department_id to user

Revision ID: 803722f2c4e4
Revises: 584667013c24
Create Date: 2023-09-24 14:23:54.361634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803722f2c4e4'
down_revision = '584667013c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tbl_department', ['department_id'], ['id_department'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
