"""old stable ver

Revision ID: 805d59ba140a
Revises: b28584f458b2
Create Date: 2023-01-21 21:48:49.026542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '805d59ba140a'
down_revision = 'b28584f458b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_map', sa.Column('id_module', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'work_map', 'tbl_aup', ['id_aup'], ['id_aup'], ondelete='CASCADE')
    op.create_foreign_key(None, 'work_map', 'tbl_module', ['id_module'], ['id_module'])
    op.add_column('workload', sa.Column('id_module', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workload', 'tbl_module', ['id_module'], ['id_module'])
    op.drop_column('workload', 'module')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workload', sa.Column('module', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'workload', type_='foreignkey')
    op.drop_column('workload', 'id_module')
    op.drop_constraint(None, 'work_map', type_='foreignkey')
    op.drop_constraint(None, 'work_map', type_='foreignkey')
    op.drop_column('work_map', 'id_module')
    # ### end Alembic commands ###
