"""change aup_info1

Revision ID: 81897a27554c
Revises: fc731787bba9
Create Date: 2023-01-30 02:19:43.593659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81897a27554c'
down_revision = 'fc731787bba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_info', schema=None) as batch_op:
        batch_op.alter_column('direction',
               existing_type=mysql.VARCHAR(length=40),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('name_spec',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_info', schema=None) as batch_op:
        batch_op.alter_column('name_spec',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.alter_column('direction',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###
