"""add weight to groups

Revision ID: 840ee06f6367
Revises: fd68bfa98bee
Create Date: 2023-03-07 13:52:04.087011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840ee06f6367'
down_revision = 'fd68bfa98bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
