"""add SprVolumeDegreeZET

Revision ID: 845c13cc448d
Revises: db24a35edb8a
Create Date: 2022-10-24 17:19:33.982807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845c13cc448d'
down_revision = 'db24a35edb8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spr_volume_degree_zet',
    sa.Column('id_volume_deg', sa.Integer(), nullable=False),
    sa.Column('id_degree', sa.Integer(), nullable=False),
    sa.Column('year_of_start', sa.Integer(), nullable=False),
    sa.Column('zet', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_degree'], ['spr_degree_education.id_degree'], ),
    sa.PrimaryKeyConstraint('id_volume_deg')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spr_volume_degree_zet')
    # ### end Alembic commands ###
