"""Add recommended_ps_parsed_data to FgosVo

Revision ID: 87d13b09e467
Revises: 05451f9d4309
Create Date: 2025-05-27 16:02:06.375365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d13b09e467'
down_revision = '05451f9d4309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competencies_fgos_vo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended_ps_parsed_data', sa.JSON(), nullable=True, comment='JSON массив рекомендованных ПС из PDF ФГОС'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competencies_fgos_vo', schema=None) as batch_op:
        batch_op.drop_column('recommended_ps_parsed_data')

    # ### end Alembic commands ###
