"""remove tblAup-faculty relationship

Revision ID: 8813d9da8065
Revises: bc215bec7084
Create Date: 2024-05-23 00:21:24.975193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8813d9da8065'
down_revision = 'bc215bec7084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_aup', schema=None) as batch_op:
        batch_op.drop_constraint('tbl_aup_ibfk_2', type_='foreignkey')
        batch_op.drop_column('id_faculty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_aup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_faculty', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('tbl_aup_ibfk_2', 'spr_faculty', ['id_faculty'], ['id_faculty'])

    # ### end Alembic commands ###
