"""add spr place

Revision ID: 8a54e69178ae
Revises: 2af0a78bdad3
Create Date: 2024-05-30 14:03:54.352721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a54e69178ae'
down_revision = '2af0a78bdad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spr_place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_22', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_21', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')

    with op.batch_alter_table('grade_column', schema=None) as batch_op:
        batch_op.drop_constraint('grade_column_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('grade_column_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('grade_column_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['id'])
        batch_op.create_foreign_key(None, 'grade_table', ['grade_table_id'], ['id'])
        batch_op.create_foreign_key(None, 'grade_type', ['grade_type_id'], ['id'])

    with op.batch_alter_table('grade_table', schema=None) as batch_op:
        batch_op.drop_constraint('grade_table_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'spr_discipline', ['id_unique_discipline'], ['id'])

    with op.batch_alter_table('grade_type', schema=None) as batch_op:
        batch_op.drop_constraint('grade_type_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'grade_table', ['grade_table_id'], ['id'])

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('grades_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('grades_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('grades_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])
        batch_op.create_foreign_key(None, 'grade_column', ['grade_column_id'], ['id'])
        batch_op.create_foreign_key(None, 'grade_table', ['grade_table_id'], ['id'])

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spr_place_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('place_note', sa.String(length=400), nullable=True))
        batch_op.create_foreign_key(None, 'spr_place', ['spr_place_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('place_note')
        batch_op.drop_column('spr_place_id')

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grades_ibfk_1', 'grade_column', ['grade_column_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key('grades_ibfk_2', 'grade_table', ['grade_table_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key('grades_ibfk_3', 'students', ['student_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')

    with op.batch_alter_table('grade_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grade_type_ibfk_1', 'grade_table', ['grade_table_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')

    with op.batch_alter_table('grade_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grade_table_ibfk_2', 'spr_discipline', ['id_unique_discipline'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')

    with op.batch_alter_table('grade_column', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grade_column_ibfk_2', 'grade_type', ['grade_type_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key('grade_column_ibfk_3', 'topic', ['topic_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
        batch_op.create_foreign_key('grade_column_ibfk_1', 'grade_table', ['grade_table_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_21', 'groups', ['id_group'], ['id_group'])
        batch_op.create_foreign_key('aup_data_ibfk_22', 'd_modules', ['id_module'], ['id'])

    op.drop_table('spr_place')
    # ### end Alembic commands ###
