"""fix gradetable & sprgrade

Revision ID: 8b8cc89e3711
Revises: 345d3c461a8c
Create Date: 2024-05-15 20:12:48.706110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8cc89e3711'
down_revision = '345d3c461a8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_table_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'grade_table', ['grade_table_id'], ['id'])

    with op.batch_alter_table('sprgrade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_table_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'grade_table', ['grade_table_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sprgrade', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grade_table_id')

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grade_table_id')

    # ### end Alembic commands ###
