"""change unification load model

Revision ID: 8bfe9f68b976
Revises: 81735b249ed3
Create Date: 2023-09-27 21:52:38.939436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfe9f68b976'
down_revision = '81735b249ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unification_load', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unification_load', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
