"""fix grades

Revision ID: 936e2e97bfc8
Revises: 9fb14ad6deb5
Create Date: 2024-05-15 21:47:12.659883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '936e2e97bfc8'
down_revision = '9fb14ad6deb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_column', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=400), nullable=False))

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_column_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('grades_ibfk_4', type_='foreignkey')
        batch_op.create_foreign_key(None, 'grade_column', ['grade_column_id'], ['id'])
        batch_op.drop_column('col_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('col_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grades_ibfk_4', 'topic', ['col_id'], ['id'])
        batch_op.drop_column('grade_column_id')

    with op.batch_alter_table('grade_column', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
