"""Add enrollment_year to EducationalProgram

Revision ID: 93e96b28aede
Revises: 92b5300b9054
Create Date: 2025-04-08 03:02:44.546758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e96b28aede'
down_revision = '92b5300b9054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_12', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_11', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')

    with op.batch_alter_table('competencies_educational_program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_year', sa.Integer(), nullable=True, comment='Год набора'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competencies_educational_program', schema=None) as batch_op:
        batch_op.drop_column('enrollment_year')

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_11', 'd_modules', ['id_module'], ['id'])
        batch_op.create_foreign_key('aup_data_ibfk_12', 'groups', ['id_group'], ['id_group'])

    # ### end Alembic commands ###
