"""add tutors order

Revision ID: 93f798bbc02a
Revises: e6fb06709ca2
Create Date: 2024-06-02 22:42:35.844793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f798bbc02a'
down_revision = 'e6fb06709ca2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutors_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_order', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['spr_faculty.id_faculty'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_22', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_21', type_='foreignkey')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_21', 'groups', ['id_group'], ['id_group'])
        batch_op.create_foreign_key('aup_data_ibfk_22', 'd_modules', ['id_module'], ['id'])

    op.drop_table('tutors_order')
    # ### end Alembic commands ###
