"""change rule association

Revision ID: 94ab3ca8723e
Revises: 45887e03d2a3
Create Date: 2023-08-14 10:57:00.606355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ab3ca8723e'
down_revision = '45887e03d2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aup_info_has_rule',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('aup_info_id', sa.Integer(), nullable=False),
    sa.Column('min', sa.Float(), nullable=True),
    sa.Column('max', sa.Float(), nullable=True),
    sa.Column('ed_izmereniya_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aup_info_id'], ['tbl_aup.id_aup'], ),
    sa.ForeignKeyConstraint(['ed_izmereniya_id'], ['d_ed_izmereniya.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['tbl_rule.id'], ),
    sa.PrimaryKeyConstraint('rule_id', 'aup_info_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aup_info_has_rule')
    # ### end Alembic commands ###
