"""add fk ed_izmerenia

Revision ID: 96007a67cb9e
Revises: 3b48567146ff
Create Date: 2023-02-16 22:09:27.609005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96007a67cb9e'
down_revision = '3b48567146ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_edizm', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'd_ed_izmereniya', ['id_edizm'], ['id_edizm'])
        batch_op.drop_column('measure')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('measure', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_edizm')

    # ### end Alembic commands ###
