"""add spr bells for topic

Revision ID: 9627c97e07f8
Revises: fcd4177f2dd5
Create Date: 2024-05-22 04:58:48.168988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9627c97e07f8'
down_revision = 'fcd4177f2dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spr_bells_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'spr_bells', ['spr_bells_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('spr_bells_id')

    # ### end Alembic commands ###
