"""add users

Revision ID: 9a5ae7c9b890
Revises: 8a2ea2942f23
Create Date: 2023-06-13 17:30:26.550904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5ae7c9b890'
down_revision = '8a2ea2942f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('id_faculty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_faculty'], ['spr_faculty.id_faculty'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('password_hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
