"""add AUP_DATA2

Revision ID: 9d3235f3811c
Revises: 28b86680b406
Create Date: 2023-01-30 02:15:37.851484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3235f3811c'
down_revision = '28b86680b406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aup_num', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_column('aup_num')

    # ### end Alembic commands ###
