"""555

Revision ID: 9f251448eff3
Revises: 16b4f5b9a2e9
Create Date: 2024-06-09 03:26:59.952504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f251448eff3'
down_revision = '16b4f5b9a2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_21', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_22', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')

    with op.batch_alter_table('tutors_order_row', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('study_group_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('tutors_order_row_ibfk_5', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tbl_department', ['department_id'], ['id_department'])
        batch_op.create_foreign_key(None, 'study_group', ['study_group_id'], ['id'])
        batch_op.drop_column('id_department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutors_order_row', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_department', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tutors_order_row_ibfk_5', 'tbl_department', ['id_department'], ['id_department'])
        batch_op.drop_column('study_group_id')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_22', 'd_modules', ['id_module'], ['id'])
        batch_op.create_foreign_key('aup_data_ibfk_21', 'groups', ['id_group'], ['id_group'])

    # ### end Alembic commands ###
