"""fix grades

Revision ID: 9fb14ad6deb5
Revises: f2ee64d4ac98
Create Date: 2024-05-15 21:40:26.568672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fb14ad6deb5'
down_revision = 'f2ee64d4ac98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_column',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_table_id', sa.Integer(), nullable=False),
    sa.Column('type_grade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_table_id'], ['grade_table.id'], ),
    sa.ForeignKeyConstraint(['type_grade_id'], ['type_grade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('spr_grade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spr_grade',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('grade_table_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['grade_table_id'], ['grade_table.id'], name='spr_grade_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('grade_column')
    op.drop_table('type_grade')
    # ### end Alembic commands ###
