"""old stable ver

Revision ID: a07b7868922c
Revises: c1b7dcba18b0
Create Date: 2023-01-21 21:52:08.876764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a07b7868922c'
down_revision = 'c1b7dcba18b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workload', 'id_module',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_foreign_key(None, 'workload', 'tbl_module', ['id_module'], ['id_module'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workload', type_='foreignkey')
    op.alter_column('workload', 'id_module',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
