"""Add relationship serialization to to_dict in models

Revision ID: a0c586ca251a
Revises: 64cc0b7d4252
Create Date: 2025-05-12 13:32:44.395266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c586ca251a'
down_revision = '64cc0b7d4252'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competencies_competency', schema=None) as batch_op:
        batch_op.drop_index('uq_competency_code_fgos')
        batch_op.create_unique_constraint('uq_competency_code_fgos_type', ['code', 'fgos_vo_id', 'competency_type_id'])

    with op.batch_alter_table('competencies_educational_program_aup', schema=None) as batch_op:
        batch_op.drop_constraint('competencies_educational_program_aup_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'competencies_educational_program', ['educational_program_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('competencies_educational_program_ps', schema=None) as batch_op:
        batch_op.drop_constraint('competencies_educational_program_ps_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('competencies_educational_program_ps_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'competencies_educational_program', ['educational_program_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'competencies_prof_standard', ['prof_standard_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('competencies_fgos_recommended_ps', schema=None) as batch_op:
        batch_op.drop_constraint('competencies_fgos_recommended_ps_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('competencies_fgos_recommended_ps_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'competencies_prof_standard', ['prof_standard_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'competencies_fgos_vo', ['fgos_vo_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('competencies_generalized_labor_function', schema=None) as batch_op:
        batch_op.drop_constraint('competencies_generalized_labor_function_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'competencies_prof_standard', ['prof_standard_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('competencies_indicator', schema=None) as batch_op:
        batch_op.drop_constraint('competencies_indicator_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'competencies_competency', ['competency_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('competencies_indicator_ps_link', schema=None) as batch_op:
        batch_op.drop_constraint('competencies_indicator_ps_link_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('competencies_indicator_ps_link_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'competencies_labor_function', ['labor_function_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'competencies_indicator', ['indicator_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('competencies_labor_action', schema=None) as batch_op:
        batch_op.drop_constraint('competencies_labor_action_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'competencies_labor_function', ['labor_function_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('competencies_labor_function', schema=None) as batch_op:
        batch_op.drop_constraint('competencies_labor_function_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'competencies_generalized_labor_function', ['generalized_labor_function_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('competencies_matrix', schema=None) as batch_op:
        batch_op.drop_constraint('competencies_matrix_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'competencies_indicator', ['indicator_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tbl_users', ['created_by'], ['id_user'])

    with op.batch_alter_table('competencies_prof_standard', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['code'])

    with op.batch_alter_table('competencies_required_knowledge', schema=None) as batch_op:
        batch_op.drop_constraint('competencies_required_knowledge_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'competencies_labor_function', ['labor_function_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('competencies_required_skill', schema=None) as batch_op:
        batch_op.drop_constraint('competencies_required_skill_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'competencies_labor_function', ['labor_function_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competencies_required_skill', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('competencies_required_skill_ibfk_1', 'competencies_labor_function', ['labor_function_id'], ['id'])

    with op.batch_alter_table('competencies_required_knowledge', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('competencies_required_knowledge_ibfk_1', 'competencies_labor_function', ['labor_function_id'], ['id'])

    with op.batch_alter_table('competencies_prof_standard', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('competencies_matrix', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('competencies_matrix_ibfk_2', 'competencies_indicator', ['indicator_id'], ['id'])

    with op.batch_alter_table('competencies_labor_function', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('competencies_labor_function_ibfk_1', 'competencies_generalized_labor_function', ['generalized_labor_function_id'], ['id'])

    with op.batch_alter_table('competencies_labor_action', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('competencies_labor_action_ibfk_1', 'competencies_labor_function', ['labor_function_id'], ['id'])

    with op.batch_alter_table('competencies_indicator_ps_link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('competencies_indicator_ps_link_ibfk_1', 'competencies_indicator', ['indicator_id'], ['id'])
        batch_op.create_foreign_key('competencies_indicator_ps_link_ibfk_2', 'competencies_labor_function', ['labor_function_id'], ['id'])

    with op.batch_alter_table('competencies_indicator', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('competencies_indicator_ibfk_1', 'competencies_competency', ['competency_id'], ['id'])

    with op.batch_alter_table('competencies_generalized_labor_function', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('competencies_generalized_labor_function_ibfk_1', 'competencies_prof_standard', ['prof_standard_id'], ['id'])

    with op.batch_alter_table('competencies_fgos_recommended_ps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('competencies_fgos_recommended_ps_ibfk_1', 'competencies_fgos_vo', ['fgos_vo_id'], ['id'])
        batch_op.create_foreign_key('competencies_fgos_recommended_ps_ibfk_2', 'competencies_prof_standard', ['prof_standard_id'], ['id'])

    with op.batch_alter_table('competencies_educational_program_ps', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('competencies_educational_program_ps_ibfk_2', 'competencies_prof_standard', ['prof_standard_id'], ['id'])
        batch_op.create_foreign_key('competencies_educational_program_ps_ibfk_1', 'competencies_educational_program', ['educational_program_id'], ['id'])

    with op.batch_alter_table('competencies_educational_program_aup', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('competencies_educational_program_aup_ibfk_2', 'competencies_educational_program', ['educational_program_id'], ['id'])

    with op.batch_alter_table('competencies_competency', schema=None) as batch_op:
        batch_op.drop_constraint('uq_competency_code_fgos_type', type_='unique')
        batch_op.create_index('uq_competency_code_fgos', ['code', 'fgos_vo_id'], unique=True)

    # ### end Alembic commands ###
