"""add aup_info1

Revision ID: a1ddb03a9239
Revises: e81a88a204be
Create Date: 2023-01-30 02:01:23.450601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1ddb03a9239'
down_revision = 'e81a88a204be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_education', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('degree', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('direction', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('program_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('name_spec', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('type_standard', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('name_faculty', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('form_educ', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('years_begin', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('period_edication', sa.String(length=30), nullable=False))
        batch_op.drop_column('level')
        batch_op.drop_column('start_year')
        batch_op.drop_column('code')
        batch_op.drop_column('profile')
        batch_op.drop_column('type')
        batch_op.drop_column('faculty')
        batch_op.drop_column('period')
        batch_op.drop_column('form')
        batch_op.drop_column('education_way')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education_way', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('form', mysql.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('period', mysql.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('faculty', mysql.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('profile', mysql.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('code', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('start_year', mysql.VARCHAR(length=30), nullable=False))
        batch_op.add_column(sa.Column('level', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('period_edication')
        batch_op.drop_column('years_begin')
        batch_op.drop_column('form_educ')
        batch_op.drop_column('name_faculty')
        batch_op.drop_column('type_standard')
        batch_op.drop_column('name_spec')
        batch_op.drop_column('program_code')
        batch_op.drop_column('direction')
        batch_op.drop_column('degree')
        batch_op.drop_column('type_education')

    # ### end Alembic commands ###
