"""change unification load model

Revision ID: a2ec0c4133d9
Revises: 8bfe9f68b976
Create Date: 2023-09-28 13:34:04.829298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ec0c4133d9'
down_revision = '8bfe9f68b976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unification_load',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unification_id', sa.Integer(), nullable=False),
    sa.Column('control_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['control_type_id'], ['d_control_type.id'], ),
    sa.ForeignKeyConstraint(['unification_id'], ['unification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unification_load')
    # ### end Alembic commands ###
