"""add unification module

Revision ID: a309d8cdcaea
Revises: 6646b414b766
Create Date: 2024-03-18 03:49:30.865120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a309d8cdcaea'
down_revision = '6646b414b766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipline_faculty_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('okso_discipline_id', sa.Integer(), nullable=False),
    sa.Column('for_all_faculty', sa.Boolean(), nullable=False),
    sa.Column('zet', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['okso_discipline_id'], ['okso_discipline.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discipline_has_faculties',
    sa.Column('discipline_faculty_relation_id', sa.Integer(), nullable=False),
    sa.Column('spr_faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_faculty_relation_id'], ['discipline_faculty_relation.id'], ),
    sa.ForeignKeyConstraint(['spr_faculty_id'], ['spr_faculty.id_faculty'], )
    )
    op.create_table('specification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('control_type_id', sa.Integer(), nullable=False),
    sa.Column('discipline_faculty_relation_id', sa.Integer(), nullable=False),
    sa.Column('lectures', sa.Float(), nullable=True),
    sa.Column('practical', sa.Float(), nullable=True),
    sa.Column('seminars', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['control_type_id'], ['d_control_type.id'], ),
    sa.ForeignKeyConstraint(['discipline_faculty_relation_id'], ['discipline_faculty_relation.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['d_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mode')
    with op.batch_alter_table('okso_discipline', schema=None) as batch_op:
        batch_op.drop_constraint('okso_discipline_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'unification', ['unification_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('okso_discipline', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('okso_discipline_ibfk_1', 'unification', ['unification_id'], ['id'])

    op.create_table('mode',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('action', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('specification')
    op.drop_table('discipline_has_faculties')
    op.drop_table('discipline_faculty_relation')
    # ### end Alembic commands ###
