"""Correct models for competencies and seeding

Revision ID: a388922067b4
Revises: 
Create Date: 2025-04-06 15:11:01.252760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a388922067b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unification_discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.String(length=255), nullable=True),
    sa.Column('is_faculties_different', sa.Boolean(), nullable=True),
    sa.Column('ugsn', sa.String(length=255), nullable=True),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.Boolean(), nullable=True),
    sa.Column('semesters_count', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['measure_id'], ['d_ed_izmereniya.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competencies_educational_program_ps',
    sa.Column('educational_program_id', sa.Integer(), nullable=False),
    sa.Column('prof_standard_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True, comment='Приоритет ПС в рамках ОП'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['educational_program_id'], ['competencies_educational_program.id'], ),
    sa.ForeignKeyConstraint(['prof_standard_id'], ['competencies_prof_standard.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('educational_program_id', 'prof_standard_id', name='uq_educational_program_ps')
    )
    op.create_table('competencies_labor_function',
    sa.Column('generalized_labor_function_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False, comment='Код ТФ, например A/01.6'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название ТФ'),
    sa.Column('qualification_level', sa.String(length=10), nullable=True, comment='Уровень квалификации'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generalized_labor_function_id'], ['competencies_generalized_labor_function.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discipline_period_assoc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unification_discipline_id', sa.Integer(), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['d_period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unification_discipline_id'], ['unification_discipline.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_department',
    sa.Column('id_department', sa.Integer(), nullable=False),
    sa.Column('name_department', sa.String(length=255), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['spr_faculty.id_faculty'], ),
    sa.PrimaryKeyConstraint('id_department')
    )
    op.create_table('tutors_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('num_order', sa.Integer(), nullable=False),
    sa.Column('spr_form_education_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('executor', sa.String(length=255), nullable=False),
    sa.Column('signer', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['spr_faculty.id_faculty'], ),
    sa.ForeignKeyConstraint(['spr_form_education_id'], ['spr_form_education.id_form'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unification_okso_assoc',
    sa.Column('unification_id', sa.Integer(), nullable=True),
    sa.Column('okso_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['okso_id'], ['spr_okco.program_code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unification_id'], ['unification_discipline.id'], ondelete='CASCADE')
    )
    op.create_table('competencies_competency',
    sa.Column('competency_type_id', sa.Integer(), nullable=False),
    sa.Column('fgos_vo_id', sa.Integer(), nullable=True),
    sa.Column('based_on_labor_function_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False, comment='Код компетенции (УК-1, ОПК-2, ПК-3...)'),
    sa.Column('name', sa.Text(), nullable=False, comment='Формулировка компетенции'),
    sa.Column('description', sa.Text(), nullable=True, comment='Дополнительное описание компетенции'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['based_on_labor_function_id'], ['competencies_labor_function.id'], ),
    sa.ForeignKeyConstraint(['competency_type_id'], ['competencies_competency_type.id'], ),
    sa.ForeignKeyConstraint(['fgos_vo_id'], ['competencies_fgos_vo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'fgos_vo_id', name='uq_competency_code_fgos')
    )
    op.create_table('competencies_labor_action',
    sa.Column('labor_function_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание трудового действия'),
    sa.Column('order', sa.Integer(), nullable=True, comment='Порядок в списке'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['labor_function_id'], ['competencies_labor_function.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competencies_required_knowledge',
    sa.Column('labor_function_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание необходимого знания'),
    sa.Column('order', sa.Integer(), nullable=True, comment='Порядок в списке'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['labor_function_id'], ['competencies_labor_function.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competencies_required_skill',
    sa.Column('labor_function_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание необходимого умения'),
    sa.Column('order', sa.Integer(), nullable=True, comment='Порядок в списке'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['labor_function_id'], ['competencies_labor_function.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculty_discipline_period',
    sa.Column('discipline_period_id', sa.Integer(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_period_id'], ['discipline_period_assoc.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['spr_faculty.id_faculty'], ondelete='CASCADE')
    )
    op.create_table('tbl_aup',
    sa.Column('id_aup', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('num_aup', sa.String(length=255), nullable=False),
    sa.Column('base', sa.String(length=255), nullable=False),
    sa.Column('id_faculty', sa.Integer(), nullable=False),
    sa.Column('id_rop', sa.Integer(), nullable=False),
    sa.Column('type_educ', sa.String(length=255), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=False),
    sa.Column('type_standard', sa.String(length=255), nullable=False),
    sa.Column('id_department', sa.Integer(), nullable=True),
    sa.Column('period_educ', sa.String(length=255), nullable=False),
    sa.Column('id_degree', sa.Integer(), nullable=False),
    sa.Column('id_form', sa.Integer(), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=True),
    sa.Column('id_spec', sa.Integer(), nullable=True),
    sa.Column('year_beg', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_degree'], ['spr_degree_education.id_degree'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_department'], ['tbl_department.id_department'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_faculty'], ['spr_faculty.id_faculty'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_form'], ['spr_form_education.id_form'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rop'], ['spr_rop.id_rop'], ),
    sa.ForeignKeyConstraint(['id_spec'], ['spr_name_op.id_spec'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_aup')
    )
    op.create_table('tbl_users',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('auth_type', sa.String(length=255), nullable=True),
    sa.Column('approved_lk', sa.Boolean(), nullable=True),
    sa.Column('request_approve_date', sa.DateTime(), nullable=True),
    sa.Column('lk_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['tbl_department.id_department'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('password_hash')
    )
    op.create_table('tutors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('lk_id', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(length=400), nullable=True),
    sa.Column('id_department', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_department'], ['tbl_department.id_department'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unification_load',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('education_form_id', sa.Integer(), nullable=True),
    sa.Column('discipline_period_assoc_id', sa.Integer(), nullable=True),
    sa.Column('lectures', sa.Float(), nullable=True),
    sa.Column('seminars', sa.Float(), nullable=True),
    sa.Column('srs', sa.Float(), nullable=True),
    sa.Column('practices', sa.Float(), nullable=True),
    sa.Column('control_type_id', sa.Integer(), nullable=True),
    sa.Column('zet', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['control_type_id'], ['d_control_type.id'], ),
    sa.ForeignKeyConstraint(['discipline_period_assoc_id'], ['discipline_period_assoc.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['education_form_id'], ['spr_form_education.id_form'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('isActual', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aup_id'], ['tbl_aup.id_aup'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aup_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aup', sa.Integer(), nullable=False),
    sa.Column('id_block', sa.Integer(), nullable=True),
    sa.Column('shifr', sa.String(length=30), nullable=False),
    sa.Column('id_part', sa.Integer(), nullable=True),
    sa.Column('id_module', sa.Integer(), nullable=True),
    sa.Column('id_group', sa.Integer(), nullable=True),
    sa.Column('id_type_record', sa.Integer(), nullable=False),
    sa.Column('id_discipline', sa.Integer(), nullable=True),
    sa.Column('discipline', sa.String(length=350), nullable=False),
    sa.Column('id_period', sa.Integer(), nullable=False),
    sa.Column('num_row', sa.Integer(), nullable=False),
    sa.Column('id_type_control', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id_edizm', sa.Integer(), nullable=False),
    sa.Column('zet', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aup'], ['tbl_aup.id_aup'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_block'], ['d_blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_discipline'], ['spr_discipline.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_edizm'], ['d_ed_izmereniya.id'], ),
    sa.ForeignKeyConstraint(['id_group'], ['groups.id_group'], ondelete='SET DEFAULT'),
    sa.ForeignKeyConstraint(['id_module'], ['d_modules.id'], ondelete='SET DEFAULT'),
    sa.ForeignKeyConstraint(['id_part'], ['d_part.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_period'], ['d_period.id'], ),
    sa.ForeignKeyConstraint(['id_type_control'], ['d_control_type.id'], ),
    sa.ForeignKeyConstraint(['id_type_record'], ['d_type_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competencies_educational_program_aup',
    sa.Column('educational_program_id', sa.Integer(), nullable=False),
    sa.Column('aup_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True, comment='Является ли этот АУП основным для программы'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aup_id'], ['tbl_aup.id_aup'], ),
    sa.ForeignKeyConstraint(['educational_program_id'], ['competencies_educational_program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('educational_program_id', 'aup_id', name='uq_educational_program_aup')
    )
    op.create_table('competencies_indicator',
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False, comment='Код индикатора (ИУК-1.1, ИОПК-2.3, ИПК-3.2...)'),
    sa.Column('formulation', sa.Text(), nullable=False, comment='Формулировка индикатора'),
    sa.Column('source', sa.String(length=255), nullable=True, comment='Источник (ФГОС, ПООП, ВУЗ, ПС...)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies_competency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'competency_id', name='uq_indicator_code_competency')
    )
    op.create_table('study_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('num_aup', sa.String(length=255), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=256), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id_role'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id_user'], ondelete='CASCADE')
    )
    op.create_table('users_faculty',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['spr_faculty.id_faculty'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id_user'], ondelete='CASCADE')
    )
    op.create_table('ChangeLog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=45), nullable=True),
    sa.Column('row_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=45), nullable=True),
    sa.Column('old', sa.String(length=500), nullable=True),
    sa.Column('new', sa.String(length=500), nullable=True),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['Revision.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competencies_indicator_ps_link',
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('labor_function_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True, comment='Оценка релевантности (от 0 до 1)'),
    sa.Column('is_manual', sa.Boolean(), nullable=True, comment='Связь установлена вручную'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['indicator_id'], ['competencies_indicator.id'], ),
    sa.ForeignKeyConstraint(['labor_function_id'], ['competencies_labor_function.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_id', 'labor_function_id', name='uq_indicator_tf')
    )
    op.create_table('competencies_matrix',
    sa.Column('aup_data_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True, comment='Оценка релевантности (от 0 до 1)'),
    sa.Column('is_manual', sa.Boolean(), nullable=True, comment='Связь установлена вручную'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='ID пользователя, создавшего связь'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aup_data_id'], ['aup_data.id'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['competencies_indicator.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aup_data_id', 'indicator_id', name='uq_matrix_aup_indicator')
    )
    op.create_table('discipline_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aup', sa.Integer(), nullable=False),
    sa.Column('id_unique_discipline', sa.Integer(), nullable=False),
    sa.Column('study_group_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aup'], ['tbl_aup.id_aup'], ),
    sa.ForeignKeyConstraint(['id_unique_discipline'], ['spr_discipline.id'], ),
    sa.ForeignKeyConstraint(['study_group_id'], ['study_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aup', sa.Integer(), nullable=False),
    sa.Column('id_unique_discipline', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('study_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aup'], ['tbl_aup.id_aup'], ),
    sa.ForeignKeyConstraint(['id_unique_discipline'], ['spr_discipline.id'], ),
    sa.ForeignKeyConstraint(['study_group_id'], ['study_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('study_group_id', sa.Integer(), nullable=False),
    sa.Column('lk_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_group_id'], ['study_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutors_order_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutors_order_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('study_group_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['tbl_department.id_department'], ),
    sa.ForeignKeyConstraint(['study_group_id'], ['study_group.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.ForeignKeyConstraint(['tutors_order_id'], ['tutors_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('min_grade', sa.Integer(), nullable=True),
    sa.Column('max_grade', sa.Integer(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('binary', sa.Boolean(), nullable=True),
    sa.Column('weight_grade', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('discipline_table_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_table_id'], ['discipline_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline_table_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=400), nullable=True),
    sa.Column('chapter', sa.String(length=400), nullable=True),
    sa.Column('id_type_control', sa.Integer(), nullable=True),
    sa.Column('task_link', sa.String(length=400), nullable=True),
    sa.Column('task_link_name', sa.String(length=255), nullable=True),
    sa.Column('completed_task_link', sa.String(length=255), nullable=True),
    sa.Column('completed_task_link_name', sa.String(length=255), nullable=True),
    sa.Column('study_group_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('lesson_order', sa.Integer(), nullable=True),
    sa.Column('spr_bells_id', sa.Integer(), nullable=True),
    sa.Column('date_task_finish', sa.DateTime(), nullable=True),
    sa.Column('date_task_finish_include', sa.Boolean(), nullable=True),
    sa.Column('spr_place_id', sa.Integer(), nullable=True),
    sa.Column('place_note', sa.String(length=400), nullable=True),
    sa.Column('note', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['discipline_table_id'], ['discipline_table.id'], ),
    sa.ForeignKeyConstraint(['id_type_control'], ['d_control_type.id'], ),
    sa.ForeignKeyConstraint(['spr_bells_id'], ['spr_bells.id'], ),
    sa.ForeignKeyConstraint(['spr_place_id'], ['spr_place.id'], ),
    sa.ForeignKeyConstraint(['study_group_id'], ['study_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_column',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline_table_id', sa.Integer(), nullable=False),
    sa.Column('grade_type_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_table_id'], ['discipline_table.id'], ),
    sa.ForeignKeyConstraint(['grade_type_id'], ['grade_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('grade_column_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_column_id'], ['grade_column.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    op.drop_table('grade_column')
    op.drop_table('topic')
    op.drop_table('grade_type')
    op.drop_table('tutors_order_row')
    op.drop_table('students')
    op.drop_table('grade_table')
    op.drop_table('discipline_table')
    op.drop_table('competencies_matrix')
    op.drop_table('competencies_indicator_ps_link')
    op.drop_table('ChangeLog')
    op.drop_table('users_faculty')
    op.drop_table('user_roles')
    op.drop_table('tbl_token')
    op.drop_table('study_group')
    op.drop_table('competencies_indicator')
    op.drop_table('competencies_educational_program_aup')
    op.drop_table('aup_data')
    op.drop_table('Revision')
    op.drop_table('unification_load')
    op.drop_table('tutors')
    op.drop_table('tbl_users')
    op.drop_table('tbl_aup')
    op.drop_table('faculty_discipline_period')
    op.drop_table('competencies_required_skill')
    op.drop_table('competencies_required_knowledge')
    op.drop_table('competencies_labor_action')
    op.drop_table('competencies_competency')
    op.drop_table('unification_okso_assoc')
    op.drop_table('tutors_order')
    op.drop_table('tbl_department')
    op.drop_table('discipline_period_assoc')
    op.drop_table('competencies_labor_function')
    op.drop_table('competencies_educational_program_ps')
    op.drop_table('unification_discipline')
    # ### end Alembic commands ###
