"""blablabla

Revision ID: a4e644537dad
Revises: 5df67b5e51ba
Create Date: 2024-05-31 03:30:37.973971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4e644537dad'
down_revision = '5df67b5e51ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_21', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_22', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discipline_table_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('grades_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'grade_table', ['discipline_table_id'], ['id'])
        batch_op.drop_column('grade_table_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_table_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grades_ibfk_3', 'grade_table', ['grade_table_id'], ['id'])
        batch_op.drop_column('discipline_table_id')

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_22', 'groups', ['id_group'], ['id_group'])
        batch_op.create_foreign_key('aup_data_ibfk_21', 'd_modules', ['id_module'], ['id'])

    # ### end Alembic commands ###
