"""empty message

Revision ID: a67d0392a2dc
Revises: 3254dc47f198
Create Date: 2024-05-27 00:19:19.651051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67d0392a2dc'
down_revision = '3254dc47f198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ChangeLog', schema=None) as batch_op:
        batch_op.drop_constraint('ChangeLog_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Revision', ['revision_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_18', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_19', type_='foreignkey')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_19', 'd_modules', ['id_module'], ['id'])
        batch_op.create_foreign_key('aup_data_ibfk_18', 'groups', ['id_group'], ['id_group'])

    with op.batch_alter_table('ChangeLog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ChangeLog_ibfk_1', 'Revision', ['revision_id'], ['id'])

    # ### end Alembic commands ###
