"""delete past auth table

Revision ID: a77edd2b3814
Revises: 4329a7c4808f
Create Date: 2025-05-04 15:29:34.820039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77edd2b3814'
down_revision = '4329a7c4808f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('control_type_short_name',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('control_type_id', sa.Integer(), nullable=False),
    sa.Column('shortname', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['control_type_id'], ['d_control_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'control_type_id')
    )
    op.create_table('users_faculty',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['spr_faculty.id_faculty'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], ondelete='CASCADE')
    )
    with op.batch_alter_table('Revision', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tbl_users', ['user_id'], ['id'])

    with op.batch_alter_table('tbl_aup', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['num_aup'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_aup', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Revision', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('users_faculty')
    op.drop_table('control_type_short_name')
    op.drop_table('tbl_users')
    # ### end Alembic commands ###
