"""fix SprVolumeDegreeZET

Revision ID: a7d0ec9b9394
Revises: c1710a032bc6
Create Date: 2022-10-24 19:56:16.558834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7d0ec9b9394'
down_revision = 'c1710a032bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spr_volume_degree_zet', 'year_of_start')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spr_volume_degree_zet', sa.Column('year_of_start', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
