"""123

Revision ID: a896a9f55d01
Revises: 163c9b7a5d59
Create Date: 2023-03-14 21:05:10.883984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a896a9f55d01'
down_revision = '163c9b7a5d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_10', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.create_foreign_key('aup_data_ibfk_10', 'd_period', ['id_period'], ['id'], onupdate='CASCADE')

    # ### end Alembic commands ###
