"""add id_aup

Revision ID: ac8e5615ca63
Revises: bbcc0cbfc005
Create Date: 2023-02-07 01:06:54.458551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8e5615ca63'
down_revision = 'bbcc0cbfc005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'work_map', 'tbl_aup', ['id_aup'], ['id_aup'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_map', type_='foreignkey')
    # ### end Alembic commands ###
