"""empty message

Revision ID: ac922bb9e301
Revises: 6a9f8e562b46
Create Date: 2022-10-31 21:52:37.983979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac922bb9e301'
down_revision = '6a9f8e562b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spr_standard_zet', 'effective_date')
    op.add_column('spr_volume_degree_zet', sa.Column('effective_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spr_volume_degree_zet', 'effective_date')
    op.add_column('spr_standard_zet', sa.Column('effective_date', sa.DATE(), nullable=False))
    # ### end Alembic commands ###
