"""old stable ver

Revision ID: b28584f458b2
Revises: 756a680e71dc
Create Date: 2023-01-21 21:48:13.180559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b28584f458b2'
down_revision = '756a680e71dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spr_volume_degree_zet', 'program_code',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'spr_volume_degree_zet', 'spr_okco', ['program_code'], ['program_code'])
    op.add_column('work_map', sa.Column('id_module', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'work_map', 'tbl_aup', ['id_aup'], ['id_aup'], ondelete='CASCADE')
    op.create_foreign_key(None, 'work_map', 'tbl_module', ['id_module'], ['id_module'])
    op.add_column('workload', sa.Column('id_module', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workload', 'tbl_module', ['id_module'], ['id_module'])
    op.drop_column('workload', 'module')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workload', sa.Column('module', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'workload', type_='foreignkey')
    op.drop_column('workload', 'id_module')
    op.drop_constraint(None, 'work_map', type_='foreignkey')
    op.drop_constraint(None, 'work_map', type_='foreignkey')
    op.drop_column('work_map', 'id_module')
    op.drop_constraint(None, 'spr_volume_degree_zet', type_='foreignkey')
    op.alter_column('spr_volume_degree_zet', 'program_code',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
