"""add unification tables

Revision ID: b6e83b182817
Revises: 94ab3ca8723e
Create Date: 2023-09-26 16:22:20.586496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e83b182817'
down_revision = '94ab3ca8723e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_num', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('program_code', sa.String(length=255), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('form_education', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['unique_discipline.id'], ),
    sa.ForeignKeyConstraint(['form_education'], ['spr_form_education.id_form'], ),
    sa.ForeignKeyConstraint(['measure_id'], ['d_ed_izmereniya.id'], ),
    # sa.ForeignKeyConstraint(['program_code'], ['spr_okco.program_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unification_load',
    sa.Column('unification_id', sa.Integer(), nullable=False),
    sa.Column('control_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['control_type_id'], ['d_control_type.id'], ),
    sa.ForeignKeyConstraint(['unification_id'], ['unification.id'], ),
    sa.PrimaryKeyConstraint('unification_id', 'control_type_id')
    )
    op.create_table('unification_period_table',
    sa.Column('unification_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['d_period.id'], ),
    sa.ForeignKeyConstraint(['unification_id'], ['unification.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unification_period_table')
    op.drop_table('unification_load')
    op.drop_table('unification')
    # ### end Alembic commands ###
