"""alter unification_discipline table

Revision ID: b74adb8e99a3
Revises: 3347eedd112e
Create Date: 2024-03-26 03:09:57.893809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74adb8e99a3'
down_revision = '3347eedd112e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unification_discipline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unification_discipline', schema=None) as batch_op:
        batch_op.drop_column('direction')

    # ### end Alembic commands ###
