"""old stable ver

Revision ID: b77d78d15761
Revises: 805d59ba140a
Create Date: 2023-01-21 21:50:22.240950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b77d78d15761'
down_revision = '805d59ba140a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_map')
    op.add_column('workload', sa.Column('id_module', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'workload', 'tbl_module', ['id_module'], ['id_module'])
    op.drop_column('workload', 'module')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workload', sa.Column('module', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'workload', type_='foreignkey')
    op.drop_column('workload', 'id_module')
    op.create_table('work_map',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('id_aup', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('discipline', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('zet', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_group', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('num_col', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('num_row', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('disc_color', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('id_module', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_group'], ['tbl_group.id_group'], name='work_map_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
