"""add work_map

Revision ID: bbcc0cbfc005
Revises: 6a19894040ee
Create Date: 2023-01-30 19:10:01.747879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbcc0cbfc005'
down_revision = '6a19894040ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aup', sa.Integer(), nullable=False),
    sa.Column('id_group', sa.Integer(), nullable=True),
    sa.Column('id_module', sa.Integer(), nullable=True),
    sa.Column('discipline', sa.String(length=255), nullable=False),
    sa.Column('zet', sa.Integer(), nullable=False),
    sa.Column('num_col', sa.Integer(), nullable=False),
    sa.Column('num_row', sa.Integer(), nullable=False),
    sa.Column('disc_color', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_map')
    # ### end Alembic commands ###
