"""alter unification_discipline table

Revision ID: bd99016f646c
Revises: b74adb8e99a3
Create Date: 2024-03-26 03:15:39.054119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd99016f646c'
down_revision = 'b74adb8e99a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unification_discipline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('measure_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'd_ed_izmereniya', ['measure_id'], ['id'])
        batch_op.drop_column('zet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unification_discipline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zet', mysql.FLOAT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('measure_id')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
