"""alter unification_discipline table

Revision ID: c03a49c2b8e4
Revises: d49fff2a53c7
Create Date: 2024-03-26 02:54:35.329532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03a49c2b8e4'
down_revision = 'd49fff2a53c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unification_discipline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semesters_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unification_discipline', schema=None) as batch_op:
        batch_op.drop_column('semesters_count')

    # ### end Alembic commands ###
