"""fix SprVolumeDegreeZET

Revision ID: c1710a032bc6
Revises: 845c13cc448d
Create Date: 2022-10-24 19:47:20.403606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1710a032bc6'
down_revision = '845c13cc448d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spr_volume_degree_zet', sa.Column('program_code', sa.String(length=255), nullable=False))
    op.add_column('spr_volume_degree_zet', sa.Column('type_standard', sa.String(length=255), nullable=False))
    op.drop_constraint('spr_volume_degree_zet_ibfk_1', 'spr_volume_degree_zet', type_='foreignkey')
    op.create_foreign_key(None, 'spr_volume_degree_zet', 'spr_okco', ['program_code'], ['program_code'])
    op.drop_column('spr_volume_degree_zet', 'id_degree')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spr_volume_degree_zet', sa.Column('id_degree', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'spr_volume_degree_zet', type_='foreignkey')
    op.create_foreign_key('spr_volume_degree_zet_ibfk_1', 'spr_volume_degree_zet', 'spr_degree_education', ['id_degree'], ['id_degree'])
    op.drop_column('spr_volume_degree_zet', 'type_standard')
    op.drop_column('spr_volume_degree_zet', 'program_code')
    # ### end Alembic commands ###
