"""old stable ver

Revision ID: c1b7dcba18b0
Revises: b77d78d15761
Create Date: 2023-01-21 21:51:30.971250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1b7dcba18b0'
down_revision = 'b77d78d15761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workload', 'id_module',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('workload', 'module')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workload', sa.Column('module', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('workload', 'id_module',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
