"""grade type add min max grade value

Revision ID: c3f8dc1a763d
Revises: ec3ea0c0ddb5
Create Date: 2024-05-16 01:16:29.549191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f8dc1a763d'
down_revision = 'ec3ea0c0ddb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_grade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_grade', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_type', schema=None) as batch_op:
        batch_op.drop_column('max_grade')
        batch_op.drop_column('min_grade')

    # ### end Alembic commands ###
