"""empty message

Revision ID: c8fdcf15c4e7
Revises: 7619a97a3322
Create Date: 2024-05-26 23:36:12.509318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8fdcf15c4e7'
down_revision = '7619a97a3322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_18', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_11', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_19', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_19', 'd_modules', ['id_module'], ['id'])
        batch_op.create_foreign_key('aup_data_ibfk_11', 'd_modules', ['id_module'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('aup_data_ibfk_18', 'groups', ['id_group'], ['id_group'])

    # ### end Alembic commands ###
