"""asdf

Revision ID: ca0c47ebbdfe
Revises: 5e1b5a316f86
Create Date: 2024-04-25 19:45:02.264801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca0c47ebbdfe'
down_revision = '5e1b5a316f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('d_control_type', schema=None) as batch_op:
        batch_op.alter_column('shortname',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('grades_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('grades_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'topic', ['topic_id'], ['id'])
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    with op.batch_alter_table('rpd', schema=None) as batch_op:
        batch_op.drop_constraint('rpd_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('rpd_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'spr_discipline', ['id_unique_discipline'], ['id'])
        batch_op.create_foreign_key(None, 'tbl_aup', ['id_aup'], ['id_aup'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=400),
               existing_nullable=False)
        batch_op.drop_constraint('students_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'study_group', ['study_group_id'], ['id'])

    with op.batch_alter_table('study_group', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('study_group_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tbl_aup', ['id_aup'], ['id_aup'])

    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_type', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('tbl_users_ibfk_1', type_='foreignkey')
        batch_op.drop_column('id_role')

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.alter_column('task_link_name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('completed_task_link',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('completed_task_link_name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('semester',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('topic_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('topic_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'rpd', ['id_rpd'], ['id'])
        batch_op.create_foreign_key(None, 'd_control_type', ['id_type_control'], ['id'])
        batch_op.create_foreign_key(None, 'study_group', ['study_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('topic_ibfk_1', 'rpd', ['id_rpd'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('topic_ibfk_2', 'd_control_type', ['id_type_control'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('semester',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('completed_task_link_name',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('completed_task_link',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('task_link_name',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               nullable=False)

    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_role', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('tbl_users_ibfk_1', 'roles', ['id_role'], ['id_role'])
        batch_op.drop_column('auth_type')

    with op.batch_alter_table('study_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('study_group_ibfk_1', 'tbl_aup', ['id_aup'], ['id_aup'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('students_ibfk_1', 'study_group', ['study_group_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.alter_column('name',
               existing_type=sa.String(length=400),
               type_=mysql.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('rpd', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('rpd_ibfk_2', 'spr_discipline', ['id_unique_discipline'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('rpd_ibfk_1', 'tbl_aup', ['id_aup'], ['id_aup'], ondelete='CASCADE')

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grades_ibfk_1', 'students', ['student_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.create_foreign_key('grades_ibfk_2', 'topic', ['topic_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
        batch_op.alter_column('value',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('d_control_type', schema=None) as batch_op:
        batch_op.alter_column('shortname',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)

    # ### end Alembic commands ###
