"""add hidden grade column

Revision ID: caafe5b4957d
Revises: 279b2bb08dd1
Create Date: 2024-06-02 20:17:45.001611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'caafe5b4957d'
down_revision = '279b2bb08dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_21', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_22', type_='foreignkey')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')

    with op.batch_alter_table('grade_column', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hiddent', sa.Boolean(), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_column', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=400), nullable=True))
        batch_op.drop_column('hiddent')

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_22', 'd_modules', ['id_module'], ['id'])
        batch_op.create_foreign_key('aup_data_ibfk_21', 'groups', ['id_group'], ['id_group'])

    # ### end Alembic commands ###
