"""add groups

Revision ID: cc78d4c0198c
Revises: 7553dac4228e
Create Date: 2023-01-30 01:24:02.780208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc78d4c0198c'
down_revision = '7553dac4228e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('name_group', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id_group')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('groups')
    # ### end Alembic commands ###
