"""fix work_maps

Revision ID: d0fc3fc06852
Revises: da4211e38dd9
Create Date: 2022-12-12 23:39:10.433244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd0fc3fc06852'
down_revision = 'da4211e38dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_map', sa.Column('id_group', sa.Integer(), nullable=True))
    op.add_column('work_map', sa.Column('id_module', sa.Integer(), nullable=False))
    op.add_column('work_map', sa.Column('num_col', sa.Integer(), nullable=False))
    op.add_column('work_map', sa.Column('num_row', sa.Integer(), nullable=False))
    op.add_column('work_map', sa.Column('disc_color', sa.String(length=8), nullable=False))
    op.create_foreign_key(None, 'work_map', 'tbl_aup', ['id_aup'], ['id_aup'], ondelete='CASCADE')
    op.create_foreign_key(None, 'work_map', 'tbl_group', ['id_group'], ['id_group'])
    op.create_foreign_key(None, 'work_map', 'tbl_module', ['id_module'], ['id_module'])
    op.drop_column('work_map', 'column')
    op.drop_column('work_map', 'number')
    op.drop_column('work_map', 'term')
    op.drop_column('work_map', 'module_color')
    op.drop_column('work_map', 'block')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_map', sa.Column('block', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('work_map', sa.Column('module_color', mysql.VARCHAR(length=30), nullable=False))
    op.add_column('work_map', sa.Column('term', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('work_map', sa.Column('number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('work_map', sa.Column('column', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'work_map', type_='foreignkey')
    op.drop_constraint(None, 'work_map', type_='foreignkey')
    op.drop_constraint(None, 'work_map', type_='foreignkey')
    op.drop_column('work_map', 'disc_color')
    op.drop_column('work_map', 'num_row')
    op.drop_column('work_map', 'num_col')
    op.drop_column('work_map', 'id_module')
    op.drop_column('work_map', 'id_group')
    # ### end Alembic commands ###
