"""empty message

Revision ID: d2b39c898980
Revises: 133fdeafa952
Create Date: 2023-02-16 16:38:15.493123

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2b39c898980'
down_revision = '133fdeafa952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'])
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id_module'])
        batch_op.create_foreign_key(None, 'd_type_record', ['id_type_record'], ['id_type_record'])
        batch_op.create_foreign_key(None, 'd_blocks', ['id_block'], ['id_block'])
        batch_op.create_foreign_key(None, 'tbl_aup', ['id_aup'], ['id_aup'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'd_period', ['id_period'], ['id_period'])
        batch_op.create_foreign_key(None, 'd_part', ['id_part'], ['id_part'])
        batch_op.drop_column('period_control_id')
        batch_op.drop_column('type_id')
        batch_op.drop_column('aup_num')
        batch_op.drop_column('type_control_id')
        batch_op.drop_column('module_id')
        batch_op.drop_column('part_id')
        batch_op.drop_column('block_id')

    with op.batch_alter_table('d_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_block', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('d_control_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_type_control', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('d_ed_izmereniya', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_edizm', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('d_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_module', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('d_period', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_period', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('d_type_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_type_record', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_group', sa.Integer(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('id_group')

    with op.batch_alter_table('d_type_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('id_type_record')

    with op.batch_alter_table('d_period', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('id_period')

    with op.batch_alter_table('d_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('id_module')

    with op.batch_alter_table('d_ed_izmereniya', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('id_edizm')

    with op.batch_alter_table('d_control_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('id_type_control')

    with op.batch_alter_table('d_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('id_block')

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('block_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('part_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('module_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type_control_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('aup_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('period_control_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
