"""add discipline foreign key to AupData

Revision ID: d4b1b8702797
Revises: f1df266de26d
Create Date: 2024-05-05 14:50:26.156062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b1b8702797'
down_revision = 'f1df266de26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_discipline', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'spr_discipline', ['id_discipline'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_discipline')

    # ### end Alembic commands ###
