"""add fk d_part

Revision ID: d5ff3f3eca80
Revises: 1f54d6ef9cf3
Create Date: 2023-02-16 19:03:25.497636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ff3f3eca80'
down_revision = '1f54d6ef9cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'd_part', ['id_part'], ['id_part'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
