"""empty message

Revision ID: d5ffc75c92b8
Revises: ac922bb9e301
Create Date: 2022-10-31 21:53:21.728107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ffc75c92b8'
down_revision = 'ac922bb9e301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spr_volume_degree_zet', sa.Column('effective_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spr_volume_degree_zet', 'effective_date')
    # ### end Alembic commands ###
