"""initial commit

Revision ID: d61b9a5c74eb
Revises: 829519eb6e34
Create Date: 2023-02-23 01:44:54.879992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61b9a5c74eb'
down_revision = '829519eb6e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d_blocks',
    sa.Column('id_block', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_block')
    )
    op.create_table('d_control_type',
    sa.Column('id_type_control', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_type_control')
    )
    op.create_table('d_ed_izmereniya',
    sa.Column('id_edizm', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_edizm')
    )
    op.create_table('d_modules',
    sa.Column('id_module', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_module')
    )
    op.create_table('d_part',
    sa.Column('id_part', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_part')
    )
    op.create_table('d_period',
    sa.Column('id_period', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_period')
    )
    op.create_table('d_type_record',
    sa.Column('id_type_record', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_type_record')
    )
    op.create_table('groups',
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('name_group', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id_group')
    )
    op.create_table('spr_branch',
    sa.Column('id_branch', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_branch')
    )
    op.create_table('spr_degree_education',
    sa.Column('id_degree', sa.Integer(), nullable=False),
    sa.Column('name_deg', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_degree')
    )
    op.create_table('spr_form_education',
    sa.Column('id_form', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_form')
    )
    op.create_table('spr_okco',
    sa.Column('program_code', sa.String(length=255), nullable=False),
    sa.Column('name_okco', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('program_code')
    )
    op.create_table('spr_rop',
    sa.Column('id_rop', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('middle_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_rop')
    )
    op.create_table('spr_standard_zet',
    sa.Column('id_standard', sa.Integer(), nullable=False),
    sa.Column('type_standard', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_standard')
    )
    op.create_table('spr_faculty',
    sa.Column('id_faculty', sa.Integer(), nullable=False),
    sa.Column('name_faculty', sa.String(length=255), nullable=False),
    sa.Column('id_branch', sa.Integer(), nullable=False),
    sa.Column('dean', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_branch'], ['spr_branch.id_branch'], ),
    sa.PrimaryKeyConstraint('id_faculty')
    )
    op.create_table('spr_name_op',
    sa.Column('id_spec', sa.Integer(), nullable=False),
    sa.Column('program_code', sa.String(length=255), nullable=False),
    sa.Column('num_profile', sa.String(length=255), nullable=False),
    sa.Column('name_spec', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['program_code'], ['spr_okco.program_code'], ),
    sa.PrimaryKeyConstraint('id_spec')
    )
    op.create_table('spr_volume_degree_zet',
    sa.Column('id_volume_deg', sa.Integer(), nullable=False),
    sa.Column('program_code', sa.String(length=255), nullable=False),
    sa.Column('id_standard', sa.Integer(), nullable=False),
    sa.Column('zet', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['program_code'], ['spr_okco.program_code'], ),
    sa.PrimaryKeyConstraint('id_volume_deg')
    )
    op.create_table('tbl_aup',
    sa.Column('id_aup', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('num_aup', sa.String(length=255), nullable=False),
    sa.Column('base', sa.String(length=255), nullable=False),
    sa.Column('id_faculty', sa.Integer(), nullable=False),
    sa.Column('id_rop', sa.Integer(), nullable=False),
    sa.Column('type_educ', sa.String(length=255), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=False),
    sa.Column('type_standard', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('period_educ', sa.String(length=255), nullable=False),
    sa.Column('id_degree', sa.Integer(), nullable=False),
    sa.Column('id_form', sa.Integer(), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=True),
    sa.Column('id_spec', sa.Integer(), nullable=False),
    sa.Column('year_beg', sa.Integer(), nullable=False),
    sa.Column('year_end', sa.Integer(), nullable=False),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_degree'], ['spr_degree_education.id_degree'], ),
    sa.ForeignKeyConstraint(['id_faculty'], ['spr_faculty.id_faculty'], ),
    sa.ForeignKeyConstraint(['id_form'], ['spr_form_education.id_form'], ),
    sa.ForeignKeyConstraint(['id_rop'], ['spr_rop.id_rop'], ),
    sa.ForeignKeyConstraint(['id_spec'], ['spr_name_op.id_spec'], ),
    sa.PrimaryKeyConstraint('id_aup')
    )
    op.create_table('aup_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aup', sa.Integer(), nullable=False),
    sa.Column('id_block', sa.Integer(), nullable=False),
    sa.Column('shifr', sa.String(length=30), nullable=False),
    sa.Column('id_part', sa.Integer(), nullable=False),
    sa.Column('id_module', sa.Integer(), nullable=False),
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('id_type_record', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.String(length=150), nullable=False),
    sa.Column('id_period', sa.Integer(), nullable=False),
    sa.Column('id_type_control', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id_edizm', sa.Integer(), nullable=False),
    sa.Column('zet', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_aup'], ['tbl_aup.id_aup'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_block'], ['d_blocks.id_block'], ),
    sa.ForeignKeyConstraint(['id_edizm'], ['d_ed_izmereniya.id_edizm'], ),
    sa.ForeignKeyConstraint(['id_group'], ['groups.id_group'], ),
    sa.ForeignKeyConstraint(['id_module'], ['d_modules.id_module'], ),
    sa.ForeignKeyConstraint(['id_part'], ['d_part.id_part'], ),
    sa.ForeignKeyConstraint(['id_period'], ['d_period.id_period'], ),
    sa.ForeignKeyConstraint(['id_type_control'], ['d_control_type.id_type_control'], ),
    sa.ForeignKeyConstraint(['id_type_record'], ['d_type_record.id_type_record'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aup_data')
    op.drop_table('tbl_aup')
    op.drop_table('spr_volume_degree_zet')
    op.drop_table('spr_name_op')
    op.drop_table('spr_faculty')
    op.drop_table('spr_standard_zet')
    op.drop_table('spr_rop')
    op.drop_table('spr_okco')
    op.drop_table('spr_form_education')
    op.drop_table('spr_degree_education')
    op.drop_table('spr_branch')
    op.drop_table('groups')
    op.drop_table('d_type_record')
    op.drop_table('d_period')
    op.drop_table('d_part')
    op.drop_table('d_modules')
    op.drop_table('d_ed_izmereniya')
    op.drop_table('d_control_type')
    op.drop_table('d_blocks')
    # ### end Alembic commands ###
