"""empty message

Revision ID: d8f492524ded
Revises: bb33aa026e3b
Create Date: 2023-02-16 17:48:12.077761

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd8f492524ded'
down_revision = 'bb33aa026e3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.alter_column('id_block',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('id_part',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('id_module',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('id_group',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('id_type_record',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('id_period',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('id_type_control',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_constraint('aup_data_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'd_blocks', ['id_block'], ['id_block'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'd_type_record', ['id_type_record'], ['id_type_record'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'd_part', ['id_part'], ['id_part'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'd_period', ['id_period'], ['id_period'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id_module'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'd_control_type', ['id_type_control'], ['id_type_control'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_3', 'd_part', ['id_part'], ['id_part'])
        batch_op.alter_column('id_type_control',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('id_period',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('id_type_record',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('id_group',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('id_module',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('id_part',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('id_block',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
