"""del models and some fix

Revision ID: d95f379187bc
Revises: 5d5a9799211c
Create Date: 2023-01-18 00:45:20.757772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd95f379187bc'
down_revision = '5d5a9799211c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_module')
    with op.batch_alter_table('spr_volume_degree_zet', schema=None) as batch_op:
        batch_op.drop_constraint('spr_volume_degree_zet_ibfk_1', type_='foreignkey')
        batch_op.drop_column('program_code')

    with op.batch_alter_table('work_map', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'tbl_group', ['id_group'], ['id_group'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_map', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('spr_volume_degree_zet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_code', mysql.VARCHAR(length=255), nullable=False))
        batch_op.create_foreign_key('spr_volume_degree_zet_ibfk_1', 'spr_okco', ['program_code'], ['program_code'])

    op.create_table('tbl_module',
    sa.Column('id_module', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name_module', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('color', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_module'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
