"""change fk in WorkMap

Revision ID: d989448a2130
Revises: d9c3aa1918ad
Create Date: 2022-12-20 00:59:19.567581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd989448a2130'
down_revision = 'd9c3aa1918ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_map', schema=None) as batch_op:
        batch_op.drop_constraint('work_map_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('work_map_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('work_map_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_map', schema=None) as batch_op:
        batch_op.create_foreign_key('work_map_ibfk_2', 'tbl_group', ['id_group'], ['id_group'])
        batch_op.create_foreign_key('work_map_ibfk_3', 'tbl_module', ['id_module'], ['id_module'])
        batch_op.create_foreign_key('work_map_ibfk_1', 'tbl_aup', ['id_aup'], ['id_aup'], ondelete='CASCADE')

    # ### end Alembic commands ###
