"""change WorkMap model

Revision ID: d9c3aa1918ad
Revises: 758889d95669
Create Date: 2022-12-20 00:43:18.446856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9c3aa1918ad'
down_revision = '758889d95669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_map', schema=None) as batch_op:
        batch_op.alter_column('id_module',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_map', schema=None) as batch_op:
        batch_op.alter_column('id_module',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
