"""add work_maps

Revision ID: da4211e38dd9
Revises: 7d5675b38afb
Create Date: 2022-12-12 14:10:45.224147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4211e38dd9'
down_revision = '7d5675b38afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aup', sa.Integer(), nullable=False),
    sa.Column('module_color', sa.String(length=30), nullable=False),
    sa.Column('block', sa.String(length=255), nullable=False),
    sa.Column('discipline', sa.String(length=255), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('zet', sa.Integer(), nullable=False),
    sa.Column('column', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_map')
    # ### end Alembic commands ###
