"""add SprStandardZET

Revision ID: db04632784dc
Revises: a7d0ec9b9394
Create Date: 2022-10-31 21:08:40.476672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db04632784dc'
down_revision = 'a7d0ec9b9394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spr_standard_zet',
    sa.Column('id_standard', sa.Integer(), nullable=False),
    sa.Column('type_standard', sa.String(length=255), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id_standard')
    )
    op.add_column('spr_volume_degree_zet', sa.Column('id_standard', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'spr_volume_degree_zet', 'spr_standard_zet', ['id_standard'], ['id_standard'])
    op.drop_column('spr_volume_degree_zet', 'type_standard')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spr_volume_degree_zet', sa.Column('type_standard', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'spr_volume_degree_zet', type_='foreignkey')
    op.drop_column('spr_volume_degree_zet', 'id_standard')
    op.drop_table('spr_standard_zet')
    # ### end Alembic commands ###
