"""del fso from aup and change tbl_duration_edu.months nullable

Revision ID: dcee4e017ed3
Revises: 1da0a4d32ddb
Create Date: 2022-10-08 15:55:29.099298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcee4e017ed3'
down_revision = '1da0a4d32ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_aup', 'fso')
    op.alter_column('tbl_duration_edu', 'months',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_duration_edu', 'months',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.add_column('tbl_aup', sa.Column('fso', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
