"""add models to workload

Revision ID: ddf5a39d52b9
Revises: bc69f2cf0641
Create Date: 2023-01-18 00:51:01.151144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf5a39d52b9'
down_revision = 'bc69f2cf0641'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workload', schema=None) as batch_op:
        batch_op.drop_column('module')

    # ### end Alembic commands ###
