"""add aup_info

Revision ID: e81a88a204be
Revises: cc78d4c0198c
Create Date: 2023-01-30 01:48:34.564120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e81a88a204be'
down_revision = 'cc78d4c0198c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aup_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.String(length=20), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('education_way', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('qualification', sa.String(length=30), nullable=False),
    sa.Column('profile', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('faculty', sa.String(length=30), nullable=False),
    sa.Column('department', sa.String(length=30), nullable=False),
    sa.Column('form', sa.String(length=30), nullable=False),
    sa.Column('start_year', sa.String(length=30), nullable=False),
    sa.Column('period', sa.String(length=30), nullable=False),
    sa.Column('base', sa.String(length=30), nullable=False),
    sa.Column('full_years', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('id_group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_group', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    op.drop_table('aup_info')
    # ### end Alembic commands ###
