"""Add CompetencyEducationalProgram table and relationships

Revision ID: e98177595542
Revises: 609072b33446
Create Date: 2025-05-24 11:58:17.741623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e98177595542'
down_revision = '609072b33446'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competencies_competency_educational_program',
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('educational_program_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies_competency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['educational_program_id'], ['competencies_educational_program.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competency_id', 'educational_program_id', name='uq_comp_ep')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('competencies_competency_educational_program')
    # ### end Alembic commands ###
