"""add control_type_shortnames table

Revision ID: e9995672322c
Revises: 6a5070535e5b
Create Date: 2024-10-29 22:13:23.557598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9995672322c'
down_revision = '6a5070535e5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_type_short_name',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('control_type_id', sa.Integer(), nullable=False),
        sa.Column('shortname', sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(['control_type_id'], ['d_control_type.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id_user'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'control_type_id')
    )
    with op.batch_alter_table('d_control_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_shortname', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('d_control_type', schema=None) as batch_op:
        batch_op.drop_column('default_shortname')

    op.drop_table('control_type_short_name')
    # ### end Alembic commands ###
