"""Add row id_field

Revision ID: ea196d56c74f
Revises: fcb27448e924
Create Date: 2024-05-26 22:13:39.085974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea196d56c74f'
down_revision = 'fcb27448e924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ChangeLog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('row_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('ChangeLog_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Revision', ['revision_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_18', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_18', 'groups', ['id_group'], ['id_group'])

    with op.batch_alter_table('ChangeLog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ChangeLog_ibfk_1', 'Revision', ['revision_id'], ['id'])
        batch_op.drop_column('row_id')

    # ### end Alembic commands ###
