"""delete

Revision ID: eb03570cd83c
Revises: 50aa103432a5
Create Date: 2023-03-19 21:55:58.816551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb03570cd83c'
down_revision = '50aa103432a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_10', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.create_foreign_key('aup_data_ibfk_10', 'groups', ['id_group'], ['id_group'], ondelete='CASCADE')

    # ### end Alembic commands ###
