"""lesson order

Revision ID: eb83e4cb9b6f
Revises: 1236bd112f40
Create Date: 2024-05-19 19:32:42.294375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb83e4cb9b6f'
down_revision = '1236bd112f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_order', sa.Integer(), nullable=True))
        batch_op.drop_column('datetime_start')
        batch_op.drop_column('datetime_finish')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datetime_finish', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('datetime_start', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('lesson_order')

    # ### end Alembic commands ###
