"""grade type add grade table id

Revision ID: ec3ea0c0ddb5
Revises: 8879d71d413b
Create Date: 2024-05-15 23:45:06.262988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3ea0c0ddb5'
down_revision = '8879d71d413b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade_table_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'grade_table', ['grade_table_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('grade_table_id')

    # ### end Alembic commands ###
