"""SprFaculty.dean to can be none

Revision ID: ee5a7663d1cd
Revises: 20b5909a4498
Create Date: 2023-06-30 19:21:51.490104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee5a7663d1cd'
down_revision = '20b5909a4498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spr_faculty', schema=None) as batch_op:
        batch_op.alter_column('dean',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spr_faculty', schema=None) as batch_op:
        batch_op.alter_column('dean',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)

    # ### end Alembic commands ###
