"""empty message

Revision ID: f1df266de26d
Revises: 5c44bb549e9b
Create Date: 2024-05-05 14:32:23.498387

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1df266de26d'
down_revision = '5c44bb549e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spr_discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id_role'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id_user'], )
    )
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_constraint('tbl_users_ibfk_1', type_='foreignkey')
        batch_op.drop_column('id_role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_role', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('tbl_users_ibfk_1', 'roles', ['id_role'], ['id_role'])

    op.drop_table('user_roles')
    op.drop_table('spr_discipline')
    # ### end Alembic commands ###
