"""fix grade

Revision ID: f2ee64d4ac98
Revises: 3b17cac5d4a0
Create Date: 2024-05-15 21:30:57.648881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2ee64d4ac98'
down_revision = '3b17cac5d4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('col_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('grades_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'topic', ['col_id'], ['id'])
        batch_op.drop_column('topic_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('grades_ibfk_1', 'topic', ['topic_id'], ['id'])
        batch_op.drop_column('col_id')

    # ### end Alembic commands ###
