"""old stable ver

Revision ID: f399baa8dbcf
Revises: a07b7868922c
Create Date: 2023-01-21 22:04:04.911081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f399baa8dbcf'
down_revision = 'a07b7868922c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spr_volume_degree_zet', 'program_code',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'spr_volume_degree_zet', 'spr_okco', ['program_code'], ['program_code'])
    op.alter_column('workload', 'id_module',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workload', 'id_module',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'spr_volume_degree_zet', type_='foreignkey')
    op.alter_column('spr_volume_degree_zet', 'program_code',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
