"""add signer

Revision ID: f8ea2ccfd8b4
Revises: f065149b3121
Create Date: 2024-06-03 01:27:45.578144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ea2ccfd8b4'
down_revision = 'f065149b3121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_22', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_21', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')

    with op.batch_alter_table('tutors_order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signer', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutors_order', schema=None) as batch_op:
        batch_op.drop_column('signer')

    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_21', 'd_modules', ['id_module'], ['id'])
        batch_op.create_foreign_key('aup_data_ibfk_22', 'groups', ['id_group'], ['id_group'])

    # ### end Alembic commands ###
