"""'Groups_tbl_upgrade'

Revision ID: facfc4ca95b8
Revises: 4329a7c4808f
Create Date: 2025-05-11 20:55:03.124446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'facfc4ca95b8'
down_revision = '4329a7c4808f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('name_role', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_role')
    )
    op.create_table('Permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('mode_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mode_id'], ['Mode.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id_role'], ondelete='CASCADE')
    )
    op.create_table('tbl_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(length=256), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=False),
    sa.Column('ttl', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id_role'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id_user'], ondelete='CASCADE')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tbl_users', ['created_by'], ['id_user'], ondelete='RESTRICT')

    with op.batch_alter_table('tbl_aup', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['num_aup'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_aup', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('is_deleted')

    op.drop_table('user_roles')
    op.drop_table('tbl_token')
    op.drop_table('Permissions')
    op.drop_table('roles')
    # ### end Alembic commands ###
