"""change aup_info

Revision ID: fc731787bba9
Revises: 9d3235f3811c
Create Date: 2023-01-30 02:18:55.735729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc731787bba9'
down_revision = '9d3235f3811c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_info', schema=None) as batch_op:
        batch_op.alter_column('direction',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_info', schema=None) as batch_op:
        batch_op.alter_column('direction',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
