"""Add def ChangeLog and Revision

Revision ID: fcb27448e924
Revises: 02eb5cd90d02
Create Date: 2024-05-26 19:22:17.274147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb27448e924'
down_revision = '02eb5cd90d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Revision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('isActual', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('aup_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aup_id'], ['tbl_aup.id_aup'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ChangeLog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=45), nullable=True),
    sa.Column('field', sa.String(length=45), nullable=True),
    sa.Column('old', sa.String(length=500), nullable=True),
    sa.Column('new', sa.String(length=500), nullable=True),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['revision_id'], ['Revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_16', type_='foreignkey')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_16', 'groups', ['id_group'], ['id_group'], ondelete='SET NULL')

    op.drop_table('ChangeLog')
    op.drop_table('Revision')
    # ### end Alembic commands ###
