"""add num_row

Revision ID: fd68bfa98bee
Revises: 1fdb0cc3c62c
Create Date: 2023-03-02 16:59:11.423344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd68bfa98bee'
down_revision = '1fdb0cc3c62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_row', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_column('num_row')

    # ### end Alembic commands ###
