"""add tutors_order_row

Revision ID: fd6b38801d41
Revises: 82b51aca56b8
Create Date: 2024-06-07 02:02:46.692659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6b38801d41'
down_revision = '82b51aca56b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutors_order_row',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_department', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_department'], ['tbl_department.id_department'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint('aup_data_ibfk_21', type_='foreignkey')
        batch_op.drop_constraint('aup_data_ibfk_22', type_='foreignkey')
        batch_op.create_foreign_key(None, 'd_modules', ['id_module'], ['id'], ondelete='SET DEFAULT')
        batch_op.create_foreign_key(None, 'groups', ['id_group'], ['id_group'], ondelete='SET DEFAULT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aup_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('aup_data_ibfk_22', 'groups', ['id_group'], ['id_group'])
        batch_op.create_foreign_key('aup_data_ibfk_21', 'd_modules', ['id_module'], ['id'])

    op.drop_table('tutors_order_row')
    # ### end Alembic commands ###
