name: Deploy production

on:
  push:
    tags:
      - "*"

jobs:
  deploy-dev:
    runs-on: self-hosted

    env:
      TAG: localhost:5050/maps-back-prod-build:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build --no-cache -t $TAG .

      - name: Push Docker Image to Local Registry
        run: |
          docker push $TAG

      - name: Restart Services with Docker Compose
        working-directory: /opt/registry-apps/maps/prod
        run: |
          docker-compose down
          docker-compose -d

