name: Deploy production

on:
  push:
    tags:
      - "*"

jobs:
  deploy-dev:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build --no-cache -t localhost:5050/maps-backend:main . 

      - name: Push Docker Image to Local Registry
        run: |
          docker push localhost:5050/maps-backend:main
          
      - name: Restart Docker Compose
        working-directory: /home/kdadmin/apps/kd/prod
        run: |
          docker-compose pull
          docker-compose up -d

