name: Deploy Competencies

on:
  push:
    branches:
      - competencies-module

jobs:
  deploy-dev:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: localhost:5050/ap-back:main

      - name: Restart Docker Compose
        working-directory: /home/kdadmin/apps/ap
        run: |
          docker compose pull ap-backend
          docker compose up -d ap-backend
