name: Deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-prod:
    if: github.ref_name == 'main'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: cp -r ./* /opt/apps_docker/apps/prod/back_prod
      - run: sudo docker-compose -f /opt/apps_docker/docker-compose.yml up -d --build back-prod 

  deploy-dev:
    if: github.ref_name == 'dev'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: cp -r ./* /opt/apps_docker/apps/dev/back_dev
      - run: sudo docker-compose -f /opt/apps_docker/docker-compose.yml up -d --build back-dev 
