name: Deploy

on:
  push:
    branches:
      - cabinet-module

jobs:
  deploy-prod:
    if: github.ref_name == 'main'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Copy repo to production directory
        run: cp -r ./* /opt/ap/back_cabinet
      - name: Rebuild docker-compose
        run: docker-compose -f /opt/ap/docker-compose.yml up -d --build back-ap
