name: Deploy

on:
  push:
    branches:
      - main
      - dev
      - test_workflow

jobs:
  deploy-test:
    # if: github.ref == 'test_workflow'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: ls -la    

  # deploy-dev:
  #   if: github.ref == 'dev'
  #   runs-on: self-hosted
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: ls -la
