name: Deploy production

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Copy repo to production directory
        run: cp -r ./* /opt/apps_docker/apps/prod/back_prod
      - name: Rebuild docker-compose
        run: docker-compose -f /opt/apps_docker/docker-compose.yml up -d --build back-prod

