name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.DEPLOY_FOR_KD_MOSPOLYTECH_ROOT }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"

      # send all files
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress . root@158.160.22.208:/var/www/backend/

      # install dependencies
      - run: ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no root@158.160.22.208 "cd /var/www/backend && pip install -r requirements.txt"

      # run gunicorn
      - run: ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no root@158.160.22.208 "cd /var/www/backend && gunicorn --reload -c gunicorn_config.py app:app"
