name: Deploy Dev
on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build --no-cache -t localhost:5050/maps-backend:dev . 

      - name: Push Docker Image to Local Registry
        run: |
          docker push localhost:5050/maps-backend:dev
          
      - name: Restart Docker Compose
        working-directory: /home/kdadmin/apps/kd/dev
        run: |
          docker compose pull 
          docker compose up -d 
